(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.make_lisp_string('loading repl-web/repl.lisp!');
console.log(internals.xstring(l1));
var l2=internals.intern('%WRITE-STRING');
var l3=internals.intern('T','COMMON-LISP');
var l4=internals.make_lisp_string('jqconsole-output');
var l5=internals.intern('*ROOT*');
var l6=internals.intern('NIL','COMMON-LISP');
var l7=internals.make_lisp_string('');
l2.fvalue=(function(){var FUNC=(function JSCL_USER_WRITESTRING(values,v1,v2,v3){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 1:v2=l3.value;
;
case 2:v3=l4;
;
default:break;
}var v4=this;
return (function(){return internals.js_to_lisp((function(){var TMP=internals.symbolValue(l5)['jqconsole'];
return TMP===undefined?l6.value:TMP;
})())!==l6.value?v2!==l6.value?internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['Write'](internals.lisp_to_js(v1),internals.lisp_to_js(v3))):internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['Write'](internals.lisp_to_js(v1),internals.lisp_to_js(v3),internals.lisp_to_js(l7))):internals.js_to_lisp(internals.symbolValue(l5)['console']['log'](internals.lisp_to_js(v1)));
})();
});
FUNC.fname='%WRITE-STRING';
return FUNC;
})();
l2;
var l8=internals.intern('LOAD-HISTORY');
var l9=internals.make_lisp_string('jqhist');
l8.fvalue=(function(){var FUNC=(function JSCL_USER_LOADHISTORY(values){internals.checkArgsAtMost(arguments.length-1,0);
var v6=this;
return (function(){return (function(v8){return (v8===null?l3.value:l6.value)!==l6.value?l6.value:internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['SetHistory'](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l5)['JSON']['parse'](internals.lisp_to_js(v8))))));
})(internals.js_to_lisp(internals.symbolValue(l5)['localStorage']['getItem'](internals.lisp_to_js(l9))));
})();
});
FUNC.fname='LOAD-HISTORY';
return FUNC;
})();
l8;
var l10=internals.intern('SAVE-HISTORY');
var l11=internals.make_lisp_string('jqhist');
l10.fvalue=(function(){var FUNC=(function JSCL_USER_SAVEHISTORY(values){internals.checkArgsAtMost(arguments.length-1,0);
var v9=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l5)['localStorage']['setItem'](internals.lisp_to_js(l11),internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l5)['JSON']['stringify'](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['GetHistory']())))))));
})();
});
FUNC.fname='SAVE-HISTORY';
return FUNC;
})();
l10;
var l12=internals.intern('%MAP-JS-OBJECT');
var l13=internals.intern('LIST','COMMON-LISP');
var l14=internals.intern('VECTOR-TO-LIST');
var l15=internals.intern('MAPCAR','COMMON-LISP');
l12.fvalue=(function(){var FUNC=(function JSCL_USER_MAPJSOBJECT(values,v11){internals.checkArgs(arguments.length-1,1);
var v12=this;
return (function(){return l15.fvalue(values,(function JSCL_USER_NIL(values,v14){internals.checkArgs(arguments.length-1,1);
var v15=this;
return l13.fvalue(values,v14,internals.js_to_lisp((function(){var TMP=v11[internals.xstring(v14)];
return TMP===undefined?l6.value:TMP;
})()));
}),l15.fvalue(internals.pv,(function JSCL_USER_NIL(values,v16){internals.checkArgs(arguments.length-1,1);
var v17=this;
return internals.js_to_lisp(v16);
}),l14.fvalue(internals.pv,internals.js_to_lisp(internals.symbolValue(l5)['Object']['keys'](internals.lisp_to_js(v11))))));
})();
});
FUNC.fname='%MAP-JS-OBJECT';
return FUNC;
})();
l12;
var l16=internals.intern('%CONSOLE-TERPRI');
var l17=internals.intern('STRING','COMMON-LISP');
var l18=internals.make_lisp_string('jqconsole-error');
l16.fvalue=(function(){var FUNC=(function JSCL_USER_CONSOLETERPRI(values){internals.checkArgsAtMost(arguments.length-1,0);
var v18=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['Write'](internals.lisp_to_js(l17.fvalue(internals.pv,'\n')),internals.lisp_to_js(l18)));
})();
});
FUNC.fname='%CONSOLE-TERPRI';
return FUNC;
})();
l16;
var l19=internals.intern('ERRMSG-PREFIX');
var l20=internals.make_lisp_string('ERROR: ');
var l21=internals.make_lisp_string('jqconsole-error');
l19.fvalue=(function(){var FUNC=(function JSCL_USER_ERRMSGPREFIX(values){internals.checkArgsAtMost(arguments.length-1,0);
var v20=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['Write'](internals.lisp_to_js(l20),internals.lisp_to_js(l21)));
})();
});
FUNC.fname='ERRMSG-PREFIX';
return FUNC;
})();
l19;
var l22=internals.intern('+ERR-CSS+');
var l23=internals.make_lisp_string('jqconsole-error');
l22.value=l23;
l22;
var l24=internals.intern('DISPLAY-CONDITION');
var l25=internals.intern('FORMAT-ERROR');
var l26=internals.intern('COMPLAINT','KEYWORD');
l26.value=l26;
var l27=internals.make_lisp_string('Required argument missing');
var l28=internals.intern('CONTROL-STRING','KEYWORD');
l28.value=l28;
var l29=internals.make_lisp_string('~A: ~A');
var l30=internals.intern('OFFSET','KEYWORD');
l30.value=l30;
var l31=internals.intern('ERROR','COMMON-LISP');
var l32=internals.intern('PRINC','COMMON-LISP');
var l33=internals.make_lisp_string(': ');
var l34=internals.intern('WRITE-STRING','COMMON-LISP');
var l35=internals.intern('CLASS-OF','COMMON-LISP');
var l36=internals.intern('CLASS-NAME','COMMON-LISP');
var l37=internals.intern('CALL-FORMATTER');
var l38=internals.make_lisp_string(': ');
l24.fvalue=(function(){var FUNC=(function JSCL_USER_DISPLAYCONDITION(values,v22,v23,v24){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 1:v23=internals.symbolValue(l22);
;
case 2:v24=l3.value;
;
default:break;
}var v25=this;
return (function(){internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['Write'](internals.lisp_to_js(l37.fvalue(internals.pv,l6.value,(function JSCL_USER_NIL(values,v34,v35,v36){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v35=l31.fvalue(internals.pv,l25,l26.value,l27,l28.value,l29,l30.value,1);
;
case 2:v36=l31.fvalue(internals.pv,l25,l26.value,l27,l28.value,l29,l30.value,5);
;
default:break;
}var v33=l6.value;
var I;
for (I=arguments.length-1-1;I>=3;I--)v33=new internals.Cons(arguments[I+1],v33);
var v37=this;
(function(){l32.fvalue(internals.pv,v35,v34);
l34.fvalue(internals.pv,l38,v34);
return l32.fvalue(internals.pv,v36,v34);
})();
return v33;
}),l36.fvalue(internals.pv,l35.fvalue(internals.pv,v22)),v22)),internals.lisp_to_js(v23)));
return v24!==l6.value?l16.fvalue(values):l6.value;
})();
});
FUNC.fname='DISPLAY-CONDITION';
return FUNC;
})();
l24;
var l39=internals.intern('TOPLEVEL');
var l40=internals.make_lisp_string('(');
var l41=internals.make_lisp_string(')');
var l42=internals.make_lisp_string('parents');
var l43=internals.make_lisp_string('~a> ');
var l44=internals.make_lisp_string('> ');
var l45=internals.intern('*PACKAGE*','COMMON-LISP');
var l46=internals.intern('PACKAGE-NAME-FOR-PROMPT');
var l47=internals.make_lisp_string('jqconsole-prompt');
var l48=internals.make_lisp_string('ERROR[!]: ~a~%');
var l49=internals.make_lisp_string('ERROR[!]: ');
var l50=internals.intern('TERPRI','COMMON-LISP');
var l51=internals.make_lisp_string('jqconsole-error');
var l52=internals.make_lisp_string('ERROR[!]: ');
var l53=internals.intern('*HANDLER-BINDINGS*');
var l54=internals.intern('%%ERROR');
var l55=internals.intern('EVAL-INTERACTIVE-INPUT');
var l56=internals.intern('ZEROP','COMMON-LISP');
var l57=internals.make_lisp_string('jqconsole-return');
var l58=internals.make_lisp_string('~S~%');
var l59=internals.intern('PRIN1','COMMON-LISP');
var l60=internals.make_lisp_string('jqconsole-return');
var l61=internals.intern('%SEXPR-INCOMPLETE');
l39.fvalue=(function(){var FUNC=(function JSCL_USER_TOPLEVEL(values){internals.checkArgsAtMost(arguments.length-1,0);
var v39=this;
return (function(){internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['RegisterMatching'](internals.lisp_to_js(l40),internals.lisp_to_js(l41),internals.lisp_to_js(l42)));
(function(v46){return internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['Write'](internals.lisp_to_js(v46),internals.lisp_to_js(l47)));
})(l37.fvalue(internals.pv,l6.value,(function JSCL_USER_NIL(values,v42,v43){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v43=l31.fvalue(internals.pv,l25,l26.value,l27,l28.value,l43,l30.value,1);
;
default:break;
}var v41=l6.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v41=new internals.Cons(arguments[I+1],v41);
var v44=this;
(function(){l32.fvalue(internals.pv,v43,v42);
return l34.fvalue(internals.pv,l44,v42);
})();
return v41;
}),l46.fvalue(internals.pv,internals.symbolValue(l45))));
return (function(v90){return internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['Prompt'](internals.lisp_to_js(l3.value),internals.lisp_to_js(v90),internals.lisp_to_js(internals.symbolFunction(l61))));
})((function JSCL_USER_NIL(values,v47){internals.checkArgs(arguments.length-1,1);
var v48=this;
return (function(){(function(){try{return (function(){try{var v64=[];
return (function(v65){return (function(){var v66=1;
var v67=[];
TBLOOP:while (true){try{switch(v66){case 1:(function(v68){return internals.bindSpecialBindings([l53],[v68],(function(){(function(){var v70=new internals.Cons(l31,(function JSCL_USER_NIL(values,v71){internals.checkArgs(arguments.length-1,1);
var v72=this;
v65=v71;
return (function(){throw new internals.TagNLX(v67,2);
})();
}));
var v73=new internals.Cons(v70,internals.symbolValue(l53));
return l53.value=v73;
})();
return (function(){try{return (function(){throw new internals.BlockNLX(v64,(function(){return (function(v77,v78){(function(){while (v77!==l6.value){v78=v77['$$jscl_car'];
if (l56.fvalue(internals.pv,internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['GetColumn']()))!==l6.value) l6.value;
 else internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['Write'](internals.lisp_to_js('\n'),internals.lisp_to_js(l57)));
internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['Write'](internals.lisp_to_js(l37.fvalue(internals.pv,l6.value,(function JSCL_USER_NIL(values,v85,v86){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v86=l31.fvalue(internals.pv,l25,l26.value,l27,l28.value,l58,l30.value,1);
;
default:break;
}var v84=l6.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v84=new internals.Cons(arguments[I+1],v84);
var v87=this;
(function(){l59.fvalue(internals.pv,v86,v85);
return l50.fvalue(internals.pv,v85);
})();
return v84;
}),v78)),internals.lisp_to_js(l60)));
l6.value;
v77=v77['$$jscl_cdr'];
}return l6.value;
})();
return l6.value;
})((function(){var FUNC=internals.symbolFunction(l13);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l55.fvalue(values,v47);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})(),l6.value);
})(),'G260');
})();
}catch (v74){v74=internals.js_to_lisp(v74);
return (internals.isNLX(v74)?l3.value:l6.value)!==l6.value?(function(){throw v74;
})():l54.fvalue(internals.pv,(function(v75){return v75!==l6.value?v75:v74;
})(internals.js_to_lisp((function(){var TMP=v74['message'];
return TMP===undefined?l6.value:TMP;
})())));
}})();
}));
})(internals.symbolValue(l53));
case 2:(function(){throw new internals.BlockNLX(v64,(function(v89){return l24.fvalue(internals.pv,v89);
})(v65),'G260');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v67) v66=JUMP.label;
 else throw JUMP;
}}return l6.value;
})();
})(l6.value);
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v64) return CF.values;
 else throw CF;
}})();
}catch (v50){v50=internals.js_to_lisp(v50);
internals.js_to_lisp(internals.symbolValue(l5)['console']['log'](internals.lisp_to_js(v50)));
return (function(v53){return internals.js_to_lisp(internals.symbolValue(l5)['jqconsole']['Write'](internals.lisp_to_js(l37.fvalue(internals.pv,l6.value,(function JSCL_USER_NIL(values,v60,v61){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v61=l31.fvalue(internals.pv,l25,l26.value,l27,l28.value,l48,l30.value,11);
;
default:break;
}var v59=l6.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v59=new internals.Cons(arguments[I+1],v59);
var v62=this;
(function(){l34.fvalue(internals.pv,l52,v60);
l32.fvalue(internals.pv,v61,v60);
return l50.fvalue(internals.pv,v60);
})();
return v59;
}),v53)),internals.lisp_to_js(l51)));
})((function(v51){return v51!==l6.value?v51:(function(v52){return v52!==l6.value?v52:v50;
})(l12.fvalue(internals.pv,v50));
})(internals.js_to_lisp((function(){var TMP=v50['message'];
return TMP===undefined?l6.value:TMP;
})())));
}})();
l10.fvalue(internals.pv);
return l39.fvalue(values);
})();
}));
})();
});
FUNC.fname='TOPLEVEL';
return FUNC;
})();
l39;
var l62=internals.intern('WEB-INIT');
var l63=internals.intern('*STANDARD-OUTPUT*','COMMON-LISP');
var l64=internals.intern('WRITE-FN','KEYWORD');
l64.value=l64;
var l65=internals.intern('KIND','KEYWORD');
l65.value=l65;
var l66=internals.intern('WEB-REPL-OUTPUT-STREAM');
var l67=internals.intern('MAKE-STREAM');
var l68=internals.intern('*ERROR-OUTPUT*','COMMON-LISP');
var l69=internals.make_lisp_string('jqconsole-error');
var l70=internals.intern('WEB-REPL-ERROR-STREAM');
var l71=internals.intern('*TRACE-OUTPUT*','COMMON-LISP');
var l72=internals.intern('HTML','KEYWORD');
l72.value=l72;
var l73=internals.intern('WELCOME-MESSAGE');
var l74=internals.make_lisp_string('load');
l62.fvalue=(function(){var FUNC=(function JSCL_USER_WEBINIT(values){internals.checkArgsAtMost(arguments.length-1,0);
var v91=this;
return (function(){l8.fvalue(internals.pv);
l63.value=l67.fvalue(internals.pv,l64.value,(function JSCL_USER_NIL(values,v93){internals.checkArgs(arguments.length-1,1);
var v94=this;
return l2.fvalue(values,v93);
}),l65.value,l66);
l68.value=l67.fvalue(internals.pv,l64.value,(function JSCL_USER_NIL(values,v95){internals.checkArgs(arguments.length-1,1);
var v96=this;
return l2.fvalue(values,v95,l3.value,l69);
}),l65.value,l70);
l71.value=internals.symbolValue(l63);
l73.fvalue(internals.pv,l72.value,l3.value);
return internals.js_to_lisp(internals.symbolValue(l5)['window']['addEventListener'](internals.lisp_to_js(l74),internals.lisp_to_js((function JSCL_USER_NIL(values){var v99=l6.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v99=new internals.Cons(arguments[I+1],v99);
var v100=this;
return l39.fvalue(values);
}))));
})();
});
FUNC.fname='WEB-INIT';
return FUNC;
})();
l62;
l62.fvalue(internals.pv);
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
