#!/usr/bin/env node
if (typeof importScripts !== 'undefined') importScripts('./jscl.js');
(function(jscl){
'use strict';
(function(internals){ var values = internals.values;var l1=internals.make_lisp_string('loading repl-node/repl.lisp!');
console.log(internals.xstring(l1));
var l2=internals.intern('*REPL*','JSCL');
l2;
var l3=internals.intern('START-REPL','JSCL');
var l4=internals.intern('WELCOME-MESSAGE','JSCL');
var l5=internals.intern('*PACKAGE*');
var l6=internals.intern('PACKAGE-NAME-FOR-PROMPT','JSCL');
var l7=internals.make_lisp_string('> ');
var l8=internals.intern('CONCAT','JSCL');
var l9=internals.intern('CLSTRING','JSCL');
var l10=internals.intern('NSUBSTITUTE');
var l11=internals.intern('%SEXPR-INCOMPLETE','JSCL');
var l12=internals.intern('NIL');
var l13=internals.intern('*ROOT*','JSCL');
var l14=internals.intern('T');
var l15=internals.intern('*ERROR-OUTPUT*');
var l16=internals.intern('FORMAT-ERROR','JSCL');
var l17=internals.intern('COMPLAINT','KEYWORD');
l17.value=l17;
var l18=internals.make_lisp_string('Required argument missing');
var l19=internals.intern('CONTROL-STRING','KEYWORD');
l19.value=l19;
var l20=internals.make_lisp_string('ERROR[!]: ~a~%~A~%');
var l21=internals.intern('OFFSET','KEYWORD');
l21.value=l21;
var l22=internals.intern('ERROR');
var l23=internals.make_lisp_string('ERROR[!]: ');
var l24=internals.intern('WRITE-STRING');
var l25=internals.intern('PRINC');
var l26=internals.intern('TERPRI');
var l27=internals.make_lisp_string('');
var l28=internals.intern('CALL-FORMATTER','JSCL');
var l29=internals.intern('*HANDLER-BINDINGS*','JSCL');
var l30=internals.intern('SERIOUS-CONDITION');
var l31=internals.make_lisp_string('~A: ~A~%');
var l32=internals.make_lisp_string(': ');
var l33=internals.intern('CLASS-OF');
var l34=internals.intern('CLASS-NAME');
var l35=internals.intern('*TRACE-OUTPUT*');
var l36=internals.intern('FROM','KEYWORD');
l36.value=l36;
var l37=internals.intern('SIGNAL');
var l38=internals.intern('FORMAT-BACKTRACE','JSCL');
var l39=internals.intern('%%ERROR','JSCL');
var l40=internals.intern('LIST');
var l41=internals.intern('EVAL-INTERACTIVE-INPUT','JSCL');
var l42=internals.intern('FRESH-LINE');
var l43=internals.intern('PRIN1');
l3.fvalue=(function(){var FUNC=(function JSCL_USER_STARTREPL(){internals.checkArgsAtMost(arguments.length,0);
var v1=this;
return (function(){l4.fvalue();
return (function(){var v3=(function JSCL_USER_NIL(){internals.checkArgsAtMost(arguments.length,0);
var v5=this;
return (function(){return internals.mvcall(l8.fvalue,l6.fvalue(internals.symbolValue(l5)),l7);
})();
});
var v4=(function JSCL_USER_NIL(v7,v8,v9,v10){internals.checkArgs(arguments.length,4);
var v11=this;
return (function(){return (function(v13){v13=l10.fvalue(internals.char_from_codepoint(10),internals.char_from_codepoint(13),v13);
return l11.fvalue(v13)!==l12.value?(function(){var F=v10;
return internals.mvcall(typeof F==='function'?F:F.fvalue,internals.newInstance(internals.symbolValue(l13)['repl']['Recoverable']));
})():((function(){try{return (function(){try{var v23=[];
return (function(v24){return internals.bindSpecialBindings([l29],[v24],(function(){(function(){var v26=new internals.Cons(l30,(function JSCL_USER_NIL(v27){internals.checkArgs(arguments.length,1);
var v28=this;
l28.fvalue(internals.symbolValue(l15),(function JSCL_USER_NIL(v30,v31,v32){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v31=l22.fvalue(l16,l17.value,l18,l19.value,l31,l21.value,1);
;
case 2:v32=l22.fvalue(l16,l17.value,l18,l19.value,l31,l21.value,5);
;
default:break;
}var v29=l12.value;
var I;
for (I=arguments.length-1;I>=3;I--)v29=new internals.Cons(arguments[I],v29);
var v33=this;
(function(){l25.fvalue(v31,v30);
l24.fvalue(l32,v30);
l25.fvalue(v32,v30);
return l26.fvalue(v30);
})();
return v29;
}),l34.fvalue(l33.fvalue(v27)),v27);
l38.fvalue(internals.symbolValue(l35),l36.value,internals.symbolFunction(l37));
return (function(){throw new internals.BlockNLX(v23,l12.value,null,'BAIL-OUT');
})();
}));
var v35=new internals.Cons(v26,internals.symbolValue(l29));
return l29.value=v35;
})();
return (function(){try{return (function(){return (function(v39,v40){(function(){while (v39!==l12.value){v40=v39.$$jscl_car;
l42.fvalue();
l43.fvalue(v40);
l26.fvalue();
l12.value;
v39=v39.$$jscl_cdr;
}return l12.value;
})();
return l12.value;
})((function(){var FUNC=internals.symbolFunction(l40);
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.mvcall(l41.fvalue,v13);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})(),l12.value);
})();
}catch (v36){return (internals.isNLX(v36)?l14.value:l12.value)!==l12.value?(function(){throw v36;
})():l39.fvalue((function(v37){return (v37===undefined?l14.value:l12.value)!==l12.value?l9.fvalue(v36):l9.fvalue(v37);
})(v36['message']));
}})();
}));
})(internals.symbolValue(l29));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v23) return CF.value;
 else throw CF;
}})();
}catch (v14){return (function(v16){return l28.fvalue(internals.symbolValue(l15),(function JSCL_USER_NIL(v18,v19,v20){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v19=l22.fvalue(l16,l17.value,l18,l19.value,l20,l21.value,11);
;
case 2:v20=l22.fvalue(l16,l17.value,l18,l19.value,l20,l21.value,15);
;
default:break;
}var v17=l12.value;
var I;
for (I=arguments.length-1;I>=3;I--)v17=new internals.Cons(arguments[I],v17);
var v21=this;
(function(){l24.fvalue(l23,v18);
l25.fvalue(v19,v18);
l26.fvalue(v18);
l25.fvalue(v20,v18);
return l26.fvalue(v18);
})();
return v17;
}),v16,l9.fvalue(v14['stack']??l27));
})((function(v15){return (v15===undefined?l14.value:l12.value)!==l12.value?l9.fvalue(v14):l9.fvalue(v15);
})(v14['message']));
}})(),internals.symbolValue(l2)['setPrompt'](internals.xstring(v3())),(function(){var F=v10;
return internals.mvcall(typeof F==='function'?F:F.fvalue,null);
})());
})(l9.fvalue(v7));
})();
});
return l2.value=internals.symbolValue(l13)['repl']['start']({input: internals.symbolValue(l13)['process']['stdin'],output: internals.symbolValue(l13)['process']['stdout'],eval: v4,writer: (function JSCL_USER_NIL(){var v43=l12.value;
var I;
for (I=arguments.length-1;I>=0;I--)v43=new internals.Cons(arguments[I],v43);
var v44=this;
return '';
}),prompt: internals.xstring(v3())});
})();
})();
});
FUNC.fname='START-REPL';
return FUNC;
})();
l3;
var l44=internals.intern('NODE-INIT','JSCL');
var l45=internals.intern('*STANDARD-OUTPUT*');
var l46=internals.intern('WRITE-FN','KEYWORD');
l46.value=l46;
var l47=internals.intern('MAKE-STREAM','JSCL');
var l48=internals.intern('SUBSEQ');
var l49=internals.intern('VECTOR-TO-LIST','JSCL');
var l50=internals.intern('MAPCAR');
var l51=internals.intern('NULL');
var l52=internals.intern('LOAD');
l44.fvalue=(function(){var FUNC=(function JSCL_USER_NODEINIT(){internals.checkArgsAtMost(arguments.length,0);
var v45=this;
return (function(){l45.value=l47.fvalue(l46.value,(function JSCL_USER_NIL(v47){internals.checkArgs(arguments.length,1);
var v48=this;
return internals.symbolValue(l13)['process']['stdout']['write'](internals.xstring(v47));
}));
l15.value=internals.symbolValue(l45);
l35.value=internals.symbolValue(l45);
return (function(v49){return l51.fvalue(v49)!==l12.value?internals.mvcall(l3.fvalue):(function(){return (function(v51,v52){(function(){while (v51!==l12.value){v52=v51.$$jscl_car;
l52.fvalue(v52);
l12.value;
v51=v51.$$jscl_cdr;
}return l12.value;
})();
return l12.value;
})(v49,l12.value);
})();
})(l50.fvalue(internals.symbolFunction(l9),l49.fvalue(l48.fvalue(internals.symbolValue(l13)['process']['argv'],2))));
})();
});
FUNC.fname='NODE-INIT';
return FUNC;
})();
l44;
l44.fvalue();
})(jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'):
typeof window !== 'undefined'? window.jscl: self.jscl )