(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.make_lisp_string('loading repl-web/repl.lisp!');
console.log(internals.xstring(l1));
var l2=internals.intern('%WRITE-STRING');
var l3=internals.intern('T','COMMON-LISP');
var l4=internals.make_lisp_string('jqconsole-output');
var l5=internals.intern('*ROOT*');
var l6=internals.make_lisp_string('jqconsole');
var l7=internals.intern('NIL','COMMON-LISP');
var l8=internals.make_lisp_string('jqconsole');
var l9=internals.make_lisp_string('Write');
var l10=internals.make_lisp_string('');
var l11=internals.make_lisp_string('jqconsole');
var l12=internals.make_lisp_string('Write');
var l13=internals.make_lisp_string('console');
var l14=internals.make_lisp_string('log');
l2.fvalue=(function(){var FUNC=(function JSCL_USER_WRITESTRING(values,v1,v2,v3){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 1:v2=l3.value;
;
case 2:v3=l4;
;
default:break;
}var v4=this;
return (function(){return internals.js_to_lisp((function(){var TMP=internals.symbolValue(l5)[internals.xstring(l6)];
return TMP===undefined?l7.value:TMP;
})())!==l7.value?v2!==l7.value?internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l8)][internals.xstring(l9)](internals.lisp_to_js(v1),internals.lisp_to_js(v3))):internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l11)][internals.xstring(l12)](internals.lisp_to_js(v1),internals.lisp_to_js(v3),internals.lisp_to_js(l10))):internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l13)][internals.xstring(l14)](internals.lisp_to_js(v1)));
})();
});
FUNC.fname='%WRITE-STRING';
return FUNC;
})();
l2;
var l15=internals.intern('LOAD-HISTORY');
var l16=internals.make_lisp_string('jqhist');
var l17=internals.make_lisp_string('localStorage');
var l18=internals.make_lisp_string('getItem');
var l19=internals.make_lisp_string('JSON');
var l20=internals.make_lisp_string('parse');
var l21=internals.make_lisp_string('jqconsole');
var l22=internals.make_lisp_string('SetHistory');
l15.fvalue=(function(){var FUNC=(function JSCL_USER_LOADHISTORY(values){internals.checkArgsAtMost(arguments.length-1,0);
var v6=this;
return (function(){return (function(v8){return (v8===null?l3.value:l7.value)!==l7.value?l7.value:internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l21)][internals.xstring(l22)](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l19)][internals.xstring(l20)](internals.lisp_to_js(v8))))));
})(internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l17)][internals.xstring(l18)](internals.lisp_to_js(l16))));
})();
});
FUNC.fname='LOAD-HISTORY';
return FUNC;
})();
l15;
var l23=internals.intern('SAVE-HISTORY');
var l24=internals.make_lisp_string('jqhist');
var l25=internals.make_lisp_string('jqconsole');
var l26=internals.make_lisp_string('GetHistory');
var l27=internals.make_lisp_string('JSON');
var l28=internals.make_lisp_string('stringify');
var l29=internals.make_lisp_string('localStorage');
var l30=internals.make_lisp_string('setItem');
l23.fvalue=(function(){var FUNC=(function JSCL_USER_SAVEHISTORY(values){internals.checkArgsAtMost(arguments.length-1,0);
var v9=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l29)][internals.xstring(l30)](internals.lisp_to_js(l24),internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l27)][internals.xstring(l28)](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l25)][internals.xstring(l26)]())))))));
})();
});
FUNC.fname='SAVE-HISTORY';
return FUNC;
})();
l23;
var l31=internals.intern('%MAP-JS-OBJECT');
var l32=internals.intern('LIST','COMMON-LISP');
var l33=internals.make_lisp_string('Object');
var l34=internals.make_lisp_string('keys');
var l35=internals.intern('VECTOR-TO-LIST');
var l36=internals.intern('MAPCAR','COMMON-LISP');
l31.fvalue=(function(){var FUNC=(function JSCL_USER_MAPJSOBJECT(values,v11){internals.checkArgs(arguments.length-1,1);
var v12=this;
return (function(){return l36.fvalue(values,(function JSCL_USER_NIL(values,v14){internals.checkArgs(arguments.length-1,1);
var v15=this;
return l32.fvalue(values,v14,internals.js_to_lisp((function(){var TMP=v11[internals.xstring(v14)];
return TMP===undefined?l7.value:TMP;
})()));
}),l36.fvalue(internals.pv,(function JSCL_USER_NIL(values,v16){internals.checkArgs(arguments.length-1,1);
var v17=this;
return internals.js_to_lisp(v16);
}),l35.fvalue(internals.pv,internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l33)][internals.xstring(l34)](internals.lisp_to_js(v11))))));
})();
});
FUNC.fname='%MAP-JS-OBJECT';
return FUNC;
})();
l31;
var l37=internals.intern('%CONSOLE-TERPRI');
var l38=internals.intern('STRING','COMMON-LISP');
var l39=internals.make_lisp_string('jqconsole-error');
var l40=internals.make_lisp_string('jqconsole');
var l41=internals.make_lisp_string('Write');
l37.fvalue=(function(){var FUNC=(function JSCL_USER_CONSOLETERPRI(values){internals.checkArgsAtMost(arguments.length-1,0);
var v18=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l40)][internals.xstring(l41)](internals.lisp_to_js(l38.fvalue(internals.pv,'\n')),internals.lisp_to_js(l39)));
})();
});
FUNC.fname='%CONSOLE-TERPRI';
return FUNC;
})();
l37;
var l42=internals.intern('ERRMSG-PREFIX');
var l43=internals.make_lisp_string('ERROR: ');
var l44=internals.make_lisp_string('jqconsole-error');
var l45=internals.make_lisp_string('jqconsole');
var l46=internals.make_lisp_string('Write');
l42.fvalue=(function(){var FUNC=(function JSCL_USER_ERRMSGPREFIX(values){internals.checkArgsAtMost(arguments.length-1,0);
var v20=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l45)][internals.xstring(l46)](internals.lisp_to_js(l43),internals.lisp_to_js(l44)));
})();
});
FUNC.fname='ERRMSG-PREFIX';
return FUNC;
})();
l42;
var l47=internals.intern('+ERR-CSS+');
var l48=internals.make_lisp_string('jqconsole-error');
l47.value=l48;
l47;
var l49=internals.intern('DISPLAY-CONDITION');
var l50=internals.make_lisp_string('~A: ~A');
var l51=internals.intern('CLASS-OF','COMMON-LISP');
var l52=internals.intern('CLASS-NAME','COMMON-LISP');
var l53=internals.intern('FORMAT','COMMON-LISP');
var l54=internals.make_lisp_string('jqconsole');
var l55=internals.make_lisp_string('Write');
l49.fvalue=(function(){var FUNC=(function JSCL_USER_DISPLAYCONDITION(values,v22,v23,v24){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 1:v23=internals.symbolValue(l47);
;
case 2:v24=l3.value;
;
default:break;
}var v25=this;
return (function(){internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l54)][internals.xstring(l55)](internals.lisp_to_js(l53.fvalue(internals.pv,l7.value,l50,l52.fvalue(internals.pv,l51.fvalue(internals.pv,v22)),v22)),internals.lisp_to_js(v23)));
return v24!==l7.value?l37.fvalue(values):l7.value;
})();
});
FUNC.fname='DISPLAY-CONDITION';
return FUNC;
})();
l49;
var l56=internals.intern('TOPLEVEL');
var l57=internals.make_lisp_string('(');
var l58=internals.make_lisp_string(')');
var l59=internals.make_lisp_string('parents');
var l60=internals.make_lisp_string('jqconsole');
var l61=internals.make_lisp_string('RegisterMatching');
var l62=internals.make_lisp_string('~a> ');
var l63=internals.intern('*PACKAGE*','COMMON-LISP');
var l64=internals.intern('PACKAGE-NAME-FOR-PROMPT');
var l65=internals.make_lisp_string('jqconsole-prompt');
var l66=internals.make_lisp_string('jqconsole');
var l67=internals.make_lisp_string('Write');
var l68=internals.make_lisp_string('console');
var l69=internals.make_lisp_string('log');
var l70=internals.make_lisp_string('message');
var l71=internals.make_lisp_string('ERROR[!]: ~a~%');
var l72=internals.make_lisp_string('jqconsole-error');
var l73=internals.make_lisp_string('jqconsole');
var l74=internals.make_lisp_string('Write');
var l75=internals.intern('*HANDLER-BINDINGS*');
var l76=internals.intern('ERROR','COMMON-LISP');
var l77=internals.make_lisp_string('message');
var l78=internals.intern('%%ERROR');
var l79=internals.intern('LENGTH','COMMON-LISP');
var l80=internals.intern('READ-FROM-STRING','COMMON-LISP');
var l81=internals.intern('EVAL-INTERACTIVE');
var l82=internals.make_lisp_string('jqconsole');
var l83=internals.make_lisp_string('GetColumn');
var l84=internals.intern('ZEROP','COMMON-LISP');
var l85=internals.make_lisp_string('jqconsole-return');
var l86=internals.make_lisp_string('jqconsole');
var l87=internals.make_lisp_string('Write');
var l88=internals.make_lisp_string('~S~%');
var l89=internals.make_lisp_string('jqconsole-return');
var l90=internals.make_lisp_string('jqconsole');
var l91=internals.make_lisp_string('Write');
var l92=internals.intern('%SEXPR-INCOMPLETE');
var l93=internals.make_lisp_string('jqconsole');
var l94=internals.make_lisp_string('Prompt');
l56.fvalue=(function(){var FUNC=(function JSCL_USER_TOPLEVEL(values){internals.checkArgsAtMost(arguments.length-1,0);
var v27=this;
return (function(){internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l60)][internals.xstring(l61)](internals.lisp_to_js(l57),internals.lisp_to_js(l58),internals.lisp_to_js(l59)));
(function(v29){return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l66)][internals.xstring(l67)](internals.lisp_to_js(v29),internals.lisp_to_js(l65)));
})(l53.fvalue(internals.pv,l7.value,l62,l64.fvalue(internals.pv,internals.symbolValue(l63))));
return (function(v56){return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l93)][internals.xstring(l94)](internals.lisp_to_js(l3.value),internals.lisp_to_js(v56),internals.lisp_to_js(internals.symbolFunction(l92))));
})((function JSCL_USER_NIL(values,v30){internals.checkArgs(arguments.length-1,1);
var v31=this;
return (function(){(function(){try{return (function(){try{var v37=[];
return (function(v38){return (function(){var v39=1;
var v40=[];
TBLOOP:while (true){try{switch(v39){case 1:(function(v41){return internals.bindSpecialBindings([l75],[v41],(function(){(function(){var v43=new internals.Cons(l76,(function JSCL_USER_NIL(values,v44){internals.checkArgs(arguments.length-1,1);
var v45=this;
v38=v44;
return (function(){throw new internals.TagNLX(v40,2);
})();
}));
var v46=new internals.Cons(v43,internals.symbolValue(l75));
return l75.value=v46;
})();
return (function(){try{return (function(){throw new internals.BlockNLX(v37,(function(){var x1=l79.fvalue(internals.pv,v30);
if (typeof x1!='number') throw 'Not a number!';
return x1>0?l3.value:l7.value;
})()!==l7.value?(function(){var v50=l80.fvalue(internals.pv,v30);
var v51=(function(){var FUNC=internals.symbolFunction(l32);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l81.fvalue(values,v50);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
return (function(){return (function(v53,v54){(function(){while (v53!==l7.value){v54=internals.car(v53);
if (l84.fvalue(internals.pv,internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l82)][internals.xstring(l83)]()))!==l7.value) l7.value;
 else internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l86)][internals.xstring(l87)](internals.lisp_to_js('\n'),internals.lisp_to_js(l85)));
internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l90)][internals.xstring(l91)](internals.lisp_to_js(l53.fvalue(internals.pv,l7.value,l88,v54)),internals.lisp_to_js(l89)));
l7.value;
v53=internals.cdr(v53);
}return l7.value;
})();
return l7.value;
})(v51,l7.value);
})();
})():l7.value,'G272');
})();
}catch (v47){v47=internals.js_to_lisp(v47);
return (internals.isNLX(v47)?l3.value:l7.value)!==l7.value?(function(){throw v47;
})():l78.fvalue(internals.pv,(function(v48){return v48!==l7.value?v48:v47;
})(internals.js_to_lisp((function(){var TMP=v47[internals.xstring(l77)];
return TMP===undefined?l7.value:TMP;
})())));
}})();
}));
})(internals.symbolValue(l75));
case 2:(function(){throw new internals.BlockNLX(v37,(function(v55){return l49.fvalue(internals.pv,v55);
})(v38),'G272');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v40) v39=JUMP.label;
 else throw JUMP;
}}return l7.value;
})();
})(l7.value);
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v37) return CF.values;
 else throw CF;
}})();
}catch (v33){v33=internals.js_to_lisp(v33);
internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l68)][internals.xstring(l69)](internals.lisp_to_js(v33)));
return (function(v36){return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l73)][internals.xstring(l74)](internals.lisp_to_js(l53.fvalue(internals.pv,l7.value,l71,v36)),internals.lisp_to_js(l72)));
})((function(v34){return v34!==l7.value?v34:(function(v35){return v35!==l7.value?v35:v33;
})(l31.fvalue(internals.pv,v33));
})(internals.js_to_lisp((function(){var TMP=v33[internals.xstring(l70)];
return TMP===undefined?l7.value:TMP;
})())));
}})();
l23.fvalue(internals.pv);
return l56.fvalue(values);
})();
}));
})();
});
FUNC.fname='TOPLEVEL';
return FUNC;
})();
l56;
var l95=internals.intern('WEB-INIT');
var l96=internals.intern('*STANDARD-OUTPUT*','COMMON-LISP');
var l97=internals.intern('WRITE-FN','KEYWORD');
l97.value=l97;
var l98=internals.intern('MAKE-STREAM');
var l99=internals.intern('*ERROR-OUTPUT*','COMMON-LISP');
var l100=internals.make_lisp_string('jqconsole-error');
var l101=internals.intern('*TRACE-OUTPUT*','COMMON-LISP');
var l102=internals.intern('HTML','KEYWORD');
l102.value=l102;
var l103=internals.intern('WELCOME-MESSAGE');
var l104=internals.make_lisp_string('load');
var l105=internals.make_lisp_string('window');
var l106=internals.make_lisp_string('addEventListener');
l95.fvalue=(function(){var FUNC=(function JSCL_USER_WEBINIT(values){internals.checkArgsAtMost(arguments.length-1,0);
var v57=this;
return (function(){l15.fvalue(internals.pv);
l96.value=l98.fvalue(internals.pv,l97.value,(function JSCL_USER_NIL(values,v59){internals.checkArgs(arguments.length-1,1);
var v60=this;
return l2.fvalue(values,v59);
}));
l99.value=l98.fvalue(internals.pv,l97.value,(function JSCL_USER_NIL(values,v61){internals.checkArgs(arguments.length-1,1);
var v62=this;
return l2.fvalue(values,v61,l3.value,l100);
}));
l101.value=internals.symbolValue(l96);
l103.fvalue(internals.pv,l102.value,l3.value);
return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l105)][internals.xstring(l106)](internals.lisp_to_js(l104),internals.lisp_to_js((function JSCL_USER_NIL(values){var v65=l7.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v65=new internals.Cons(arguments[I+1],v65);
var v66=this;
return l56.fvalue(values);
}))));
})();
});
FUNC.fname='WEB-INIT';
return FUNC;
})();
l95;
l95.fvalue(internals.pv);
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
