if (typeof importScripts !== 'undefined') importScripts('./jscl.js');
(function(jscl){
'use strict';
(function(internals){ var values = internals.values;var l1=internals.make_lisp_string('loading deno/repl.lisp!');
console.log(internals.xstring(l1));
var l2=internals.intern('*RL*','JSCL');
l2;
var l3=internals.intern('START-REPL','JSCL');
var l4=internals.intern('WELCOME-MESSAGE','JSCL');
var l5=internals.intern('*ROOT*','JSCL');
var l6=internals.intern('MAKE-STRING-OUTPUT-STREAM');
var l7=internals.intern('NIL');
var l8=internals.intern('*PACKAGE*');
var l9=internals.intern('PACKAGE-NAME-FOR-PROMPT','JSCL');
var l10=internals.intern('FORMAT-ERROR','JSCL');
var l11=internals.intern('COMPLAINT','KEYWORD');
l11.value=l11;
var l12=internals.make_lisp_string('Required argument missing');
var l13=internals.intern('CONTROL-STRING','KEYWORD');
l13.value=l13;
var l14=internals.make_lisp_string('~a> ');
var l15=internals.intern('OFFSET','KEYWORD');
l15.value=l15;
var l16=internals.intern('ERROR');
var l17=internals.intern('PRINC');
var l18=internals.make_lisp_string('> ');
var l19=internals.intern('WRITE-STRING');
var l20=internals.intern('CALL-FORMATTER','JSCL');
var l21=internals.make_lisp_string('> ');
var l22=internals.intern('LENGTH');
var l23=internals.intern('1+');
var l24=internals.intern('INITIAL-ELEMENT','KEYWORD');
l24.value=l24;
var l25=internals.intern('MAKE-STRING');
var l26=internals.make_lisp_string(' ');
var l27=internals.intern('CONCAT','JSCL');
var l28=internals.intern('CLSTRING','JSCL');
var l29=internals.intern('WRITE-LINE');
var l30=internals.intern('STREAM-DATA','JSCL');
var l31=internals.intern('%SEXPR-INCOMPLETE','JSCL');
var l32=internals.intern('T');
var l33=internals.intern('*ERROR-OUTPUT*');
var l34=internals.make_lisp_string('ERROR[!]: ~a~%~A~%');
var l35=internals.make_lisp_string('ERROR[!]: ');
var l36=internals.intern('TERPRI');
var l37=internals.make_lisp_string('');
var l38=internals.intern('*HANDLER-BINDINGS*','JSCL');
var l39=internals.intern('SERIOUS-CONDITION');
var l40=internals.make_lisp_string('~A: ~A~%');
var l41=internals.make_lisp_string(': ');
var l42=internals.intern('CLASS-OF');
var l43=internals.intern('CLASS-NAME');
var l44=internals.intern('*TRACE-OUTPUT*');
var l45=internals.intern('FROM','KEYWORD');
l45.value=l45;
var l46=internals.intern('SIGNAL');
var l47=internals.intern('FORMAT-BACKTRACE','JSCL');
var l48=internals.intern('%%ERROR','JSCL');
var l49=internals.intern('LIST');
var l50=internals.intern('EVAL-INTERACTIVE-INPUT','JSCL');
var l51=internals.intern('FRESH-LINE');
var l52=internals.intern('PRIN1');
var l53=internals.intern('SET-FILL-POINTER','JSCL');
var l54=internals.make_lisp_string('ERROR[!]: ');
var l55=internals.make_lisp_string(': ');
l3.fvalue=(function(){var FUNC=(function JSCL_USER_STARTREPL(){internals.checkArgsAtMost(arguments.length,0);
var v1=this;
return (function(){l4.fvalue();
l2.value=internals.symbolValue(l5)['readline']['createInterface'](internals.symbolValue(l5)['process']['stdin'],internals.symbolValue(l5)['process']['stdout']);
return (function(v3,v4){return (function(v18){v18();
internals.symbolValue(l2)['prompt']();
return internals.symbolValue(l2)['on']('line',(function JSCL_USER_NIL(v54){internals.checkArgs(arguments.length,1);
var v55=this;
l29.fvalue(l28.fvalue(v54),v3);
(function(v56){return l31.fvalue(v56)!==l7.value?internals.symbolValue(l2)['setPrompt'](internals.xstring(v4)):((function(){try{return (function(){try{var v66=[];
return (function(v67){return internals.bindSpecialBindings([l38],[v67],(function(){(function(){var v69=new internals.Cons(l39,(function JSCL_USER_NIL(v70){internals.checkArgs(arguments.length,1);
var v71=this;
l20.fvalue(internals.symbolValue(l33),(function JSCL_USER_NIL(v73,v74,v75){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v74=l16.fvalue(l10,l11.value,l12,l13.value,l40,l15.value,1);
;
case 2:v75=l16.fvalue(l10,l11.value,l12,l13.value,l40,l15.value,5);
;
default:break;
}var v72=l7.value;
var I;
for (I=arguments.length-1;I>=3;I--)v72=new internals.Cons(arguments[I],v72);
var v76=this;
(function(){l17.fvalue(v74,v73);
l19.fvalue(l55,v73);
l17.fvalue(v75,v73);
return l36.fvalue(v73);
})();
return internals.values1(v72);
}),l43.fvalue(l42.fvalue(v70)),v70);
l47.fvalue(internals.symbolValue(l44),l45.value,internals.symbolFunction(l46));
return (function(){throw new internals.BlockNLX(v66,l7.value,null,'BAIL-OUT');
})();
}));
var v78=new internals.Cons(v69,internals.symbolValue(l38));
return l38.value=v78;
})();
return (function(){try{return (function(){return (function(v82,v83){(function(){while (v82!==l7.value){v83=v82.$$jscl_car;
l51.fvalue();
l52.fvalue(v83);
l36.fvalue();
l7.value;
v82=v82.$$jscl_cdr;
}return l7.value;
})();
return l7.value;
})((function(){var FUNC=internals.symbolFunction(l49);
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.mvcall(l50.fvalue,v56);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})(),l7.value);
})();
}catch (v79){return (internals.isNLX(v79)?l32.value:l7.value)!==l7.value?(function(){throw v79;
})():l48.fvalue((function(v80){return (v80===undefined?l32.value:l7.value)!==l7.value?l28.fvalue(v79):l28.fvalue(v80);
})(v79['message']));
}})();
}));
})(internals.symbolValue(l38));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v66) return CF.value;
 else throw CF;
}})();
}catch (v57){return (function(v59){return l20.fvalue(internals.symbolValue(l33),(function JSCL_USER_NIL(v61,v62,v63){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v62=l16.fvalue(l10,l11.value,l12,l13.value,l34,l15.value,11);
;
case 2:v63=l16.fvalue(l10,l11.value,l12,l13.value,l34,l15.value,15);
;
default:break;
}var v60=l7.value;
var I;
for (I=arguments.length-1;I>=3;I--)v60=new internals.Cons(arguments[I],v60);
var v64=this;
(function(){l19.fvalue(l54,v61);
l17.fvalue(v62,v61);
l36.fvalue(v61);
l17.fvalue(v63,v61);
return l36.fvalue(v61);
})();
return internals.values1(v60);
}),v59,l28.fvalue(v57['stack']??l37));
})((function(v58){return (v58===undefined?l32.value:l7.value)!==l7.value?l28.fvalue(v57):l28.fvalue(v58);
})(v57['message']));
}})(),(function(){var v85=l30.fvalue(v3);
return (function(){var FUNC=(function JSCL_USER_NIL(v87){switch(arguments.length){case 0:v87=l7.value;
;
default:break;
}var v86=l7.value;
var I;
for (I=arguments.length-1;I>=1;I--)v86=new internals.Cons(arguments[I],v86);
var v88=this;
return internals.mvcall(l53.fvalue,v85,v87);
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1(0);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})(),v18());
})(l30.fvalue(v3));
return internals.symbolValue(l2)['prompt']();
}));
})((function JSCL_USER_NIL(){internals.checkArgsAtMost(arguments.length,0);
var v5=this;
return (function(){return (function(v7){internals.symbolValue(l2)['setPrompt'](internals.xstring(l20.fvalue(l7.value,(function JSCL_USER_NIL(v14,v15){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v15=l16.fvalue(l10,l11.value,l12,l13.value,l14,l15.value,1);
;
default:break;
}var v13=l7.value;
var I;
for (I=arguments.length-1;I>=2;I--)v13=new internals.Cons(arguments[I],v13);
var v16=this;
(function(){l17.fvalue(v15,v14);
return l19.fvalue(l21,v14);
})();
return internals.values1(v13);
}),v7)));
return v4=l27.fvalue(l25.fvalue(l23.fvalue(l22.fvalue(v7)),l24.value,'.'),l26);
})(l9.fvalue(internals.symbolValue(l8)));
})();
}));
})(l6.fvalue(),l7.value);
})();
});
FUNC.fname=internals.make_lisp_string('START-REPL');
return FUNC;
})();
l3;
var l56=internals.intern('DENO-INIT','JSCL');
var l57=internals.intern('*STANDARD-OUTPUT*');
var l58=internals.intern('WRITE-FN','KEYWORD');
l58.value=l58;
var l59=internals.intern('MAKE-STREAM','JSCL');
var l60=internals.intern('SUBSEQ');
var l61=internals.intern('VECTOR-TO-LIST','JSCL');
var l62=internals.intern('MAPCAR');
var l63=internals.intern('NULL');
var l64=internals.intern('LOAD');
l56.fvalue=(function(){var FUNC=(function JSCL_USER_DENOINIT(){internals.checkArgsAtMost(arguments.length,0);
var v89=this;
return (function(){l57.value=l59.fvalue(l58.value,(function JSCL_USER_NIL(v91){internals.checkArgs(arguments.length,1);
var v92=this;
return internals.symbolValue(l5)['process']['stdout']['write'](internals.xstring(v91));
}));
l33.value=internals.symbolValue(l57);
l44.value=internals.symbolValue(l57);
return (function(v93){return l63.fvalue(v93)!==l7.value?internals.mvcall(l3.fvalue):(function(){return (function(v95,v96){(function(){while (v95!==l7.value){v96=v95.$$jscl_car;
l64.fvalue(v96);
l7.value;
v95=v95.$$jscl_cdr;
}return l7.value;
})();
return internals.values1(l7.value);
})(v93,l7.value);
})();
})(l62.fvalue(internals.symbolFunction(l28),l61.fvalue(l60.fvalue(internals.symbolValue(l5)['process']['argv'],2))));
})();
});
FUNC.fname=internals.make_lisp_string('DENO-INIT');
return FUNC;
})();
l56;
l56.fvalue();
})(jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'):
typeof window !== 'undefined'? window.jscl: self.jscl )