if (typeof importScripts !== 'undefined') importScripts('./jscl.js');
(function(jscl){
'use strict';
(function(values, internals){var l1=internals.intern('*PACKAGE*');
var l2=internals.intern('JSCL','KEYWORD');
l2.value=l2;
var l3=internals.intern('FIND-PACKAGE-OR-FAIL','JSCL');
l1.value=l3.fvalue(internals.pv,l2);
var l4=internals.make_lisp_string('loading worker.lisp!');
console.log(internals.xstring(l4));
var l5=internals.intern('*WEB-WORKER-SESSION-ID*','JSCL');
l5;
var l6=internals.intern('%WEB-WORKER-WRITE-STRING','JSCL');
var l7=internals.make_lisp_string('jqconsole-output');
var l8=internals.make_lisp_string('command');
var l9=internals.intern('NIL');
var l10=internals.make_lisp_string('output');
var l11=internals.make_lisp_string('stringclass');
var l12=internals.make_lisp_string('string');
var l13=internals.intern('*ROOT*','JSCL');
l6.fvalue=(function(){var FUNC=(function JSCL_USER_WEBWORKERWRITESTRING(values,v1,v2){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 1:v2=l7;
;
default:break;
}var v3=this;
return (function(){return (function(v5){(function(){var v7=v5;
var v8=l8;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v10){switch(arguments.length-1){case 0:v10=l9.value;
;
default:break;
}var v9=l9.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v9=new internals.Cons(arguments[I+1],v9);
var v11=this;
return (function(){var OBJ=v7;
var TMP=OBJ[internals.xstring(v8)]=internals.lisp_to_js(v10);
return TMP===undefined?l9.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l10;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v13=v5;
var v14=l11;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v16){switch(arguments.length-1){case 0:v16=l9.value;
;
default:break;
}var v15=l9.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v15=new internals.Cons(arguments[I+1],v15);
var v17=this;
return (function(){var OBJ=v13;
var TMP=OBJ[internals.xstring(v14)]=internals.lisp_to_js(v16);
return TMP===undefined?l9.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v2;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v19=v5;
var v20=l12;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v22){switch(arguments.length-1){case 0:v22=l9.value;
;
default:break;
}var v21=l9.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v21=new internals.Cons(arguments[I+1],v21);
var v23=this;
return (function(){var OBJ=v19;
var TMP=OBJ[internals.xstring(v20)]=internals.lisp_to_js(v22);
return TMP===undefined?l9.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v1;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return internals.js_to_lisp(internals.symbolValue(l13)['postMessage'](internals.lisp_to_js(v5)));
})({});
})();
});
FUNC.fname='%WEB-WORKER-WRITE-STRING';
return FUNC;
})();
l6;
var l14=internals.intern('WEB-WORKER-REPL','JSCL');
var l15=internals.intern('PACKAGE-NAME-FOR-PROMPT','JSCL');
var l16=internals.make_lisp_string('> ');
var l17=internals.intern('CONCAT','JSCL');
var l18=internals.make_lisp_string('jqconsole-prompt');
var l19=internals.intern('*ERROR-OUTPUT*');
var l20=internals.intern('FORMAT-ERROR','JSCL');
var l21=internals.intern('COMPLAINT','KEYWORD');
l21.value=l21;
var l22=internals.make_lisp_string('Required argument missing');
var l23=internals.intern('CONTROL-STRING','KEYWORD');
l23.value=l23;
var l24=internals.make_lisp_string('ERROR[!]: ~a~%~A~%');
var l25=internals.intern('OFFSET','KEYWORD');
l25.value=l25;
var l26=internals.intern('ERROR');
var l27=internals.make_lisp_string('ERROR[!]: ');
var l28=internals.intern('WRITE-STRING');
var l29=internals.intern('PRINC');
var l30=internals.intern('TERPRI');
var l31=internals.intern('CALL-FORMATTER','JSCL');
var l32=internals.intern('*HANDLER-BINDINGS*','JSCL');
var l33=internals.intern('SERIOUS-CONDITION');
var l34=internals.make_lisp_string('~A: ~A~%');
var l35=internals.make_lisp_string(': ');
var l36=internals.intern('CLASS-OF');
var l37=internals.intern('CLASS-NAME');
var l38=internals.intern('*TRACE-OUTPUT*');
var l39=internals.intern('FROM','KEYWORD');
l39.value=l39;
var l40=internals.intern('SIGNAL');
var l41=internals.intern('FORMAT-BACKTRACE','JSCL');
var l42=internals.intern('T');
var l43=internals.intern('%%ERROR','JSCL');
var l44=internals.intern('LIST');
var l45=internals.intern('READ');
var l46=internals.intern('EVAL-INTERACTIVE','JSCL');
var l47=internals.intern('FRESH-LINE');
var l48=internals.intern('PRIN1');
l14.fvalue=(function(){var FUNC=(function JSCL_USER_WEBWORKERREPL(values){internals.checkArgsAtMost(arguments.length-1,0);
var v24=this;
return (function(){return (function(){return (function(){var v27=1;
var v28=[];
TBLOOP:while (true){try{switch(v27){case 1:{l6.fvalue(internals.pv,l17.fvalue(internals.pv,l15.fvalue(internals.pv,internals.symbolValue(l1)),l16),l18);
(function(){try{return (function(){try{var v38=[];
return (function(v39){return internals.bindSpecialBindings([l32],[v39],(function(){(function(){var v41=new internals.Cons(l33,(function JSCL_USER_NIL(values,v42){internals.checkArgs(arguments.length-1,1);
var v43=this;
l31.fvalue(internals.pv,internals.symbolValue(l19),(function JSCL_USER_NIL(values,v45,v46,v47){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v46=l26.fvalue(internals.pv,l20,l21.value,l22,l23.value,l34,l25.value,1);
;
case 2:v47=l26.fvalue(internals.pv,l20,l21.value,l22,l23.value,l34,l25.value,5);
;
default:break;
}var v44=l9.value;
var I;
for (I=arguments.length-1-1;I>=3;I--)v44=new internals.Cons(arguments[I+1],v44);
var v48=this;
(function(){l29.fvalue(internals.pv,v46,v45);
l28.fvalue(internals.pv,l35,v45);
l29.fvalue(internals.pv,v47,v45);
return l30.fvalue(internals.pv,v45);
})();
return v44;
}),l37.fvalue(internals.pv,l36.fvalue(internals.pv,v42)),v42);
l41.fvalue(internals.pv,internals.symbolValue(l38),l39.value,internals.symbolFunction(l40));
return (function(){throw new internals.BlockNLX(v38,l9.value,'BAIL-OUT');
})();
}));
var v50=new internals.Cons(v41,internals.symbolValue(l32));
return l32.value=v50;
})();
return (function(){try{return (function(){return (function(v54,v55){(function(){while (v54!==l9.value){v55=v54.$$jscl_car;
l47.fvalue(internals.pv);
l48.fvalue(internals.pv,v55);
l30.fvalue(internals.pv);
l9.value;
v54=v54.$$jscl_cdr;
}return l9.value;
})();
return l9.value;
})((function(){var FUNC=internals.symbolFunction(l44);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l46.fvalue(values,l45.fvalue(internals.pv));
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})(),l9.value);
})();
}catch (v51){v51=internals.js_to_lisp(v51);
return (internals.isNLX(v51)?l42.value:l9.value)!==l9.value?(function(){throw v51;
})():l43.fvalue(internals.pv,(function(v52){return v52!==l9.value?v52:v51;
})(internals.js_to_lisp((function(){var TMP=v51['message'];
return TMP===undefined?l9.value:TMP;
})())));
}})();
}));
})(internals.symbolValue(l32));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v38) return CF.values;
 else throw CF;
}})();
}catch (v29){v29=internals.js_to_lisp(v29);
return (function(v31){return l31.fvalue(internals.pv,internals.symbolValue(l19),(function JSCL_USER_NIL(values,v33,v34,v35){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v34=l26.fvalue(internals.pv,l20,l21.value,l22,l23.value,l24,l25.value,11);
;
case 2:v35=l26.fvalue(internals.pv,l20,l21.value,l22,l23.value,l24,l25.value,15);
;
default:break;
}var v32=l9.value;
var I;
for (I=arguments.length-1-1;I>=3;I--)v32=new internals.Cons(arguments[I+1],v32);
var v36=this;
(function(){l28.fvalue(internals.pv,l27,v33);
l29.fvalue(internals.pv,v34,v33);
l30.fvalue(internals.pv,v33);
l29.fvalue(internals.pv,v35,v33);
return l30.fvalue(internals.pv,v33);
})();
return v32;
}),v31,internals.js_to_lisp((function(){var TMP=v29['stack'];
return TMP===undefined?l9.value:TMP;
})()));
})((function(v30){return v30!==l9.value?v30:v29;
})(internals.js_to_lisp((function(){var TMP=v29['message'];
return TMP===undefined?l9.value:TMP;
})())));
}})();
}(function(){throw new internals.TagNLX(v28,1);
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v28) v27=JUMP.label;
 else throw JUMP;
}}return l9.value;
})();
})();
})();
});
FUNC.fname='WEB-WORKER-REPL';
return FUNC;
})();
l14;
var l49=internals.intern('SW-REQUEST-SYNC','JSCL');
var l50=internals.intern('MAKE-NEW','JSCL');
var l51=internals.make_lisp_string('command');
var l52=internals.make_lisp_string('sessionId');
var l53=internals.make_lisp_string('options');
var l54=internals.make_lisp_string('POST');
var l55=internals.make_lisp_string('__jscl');
var l56=internals.make_lisp_string('ContentType');
var l57=internals.make_lisp_string('application/json');
var l58=internals.intern('EQL');
var l59=internals.make_lisp_string('wait');
var l60=internals.make_lisp_string('Could not contact with the service worker.');
l49.fvalue=(function(){var FUNC=(function JSCL_USER_SWREQUESTSYNC(values,v56,v57){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 1:v57={};
;
default:break;
}var v58=this;
return (function(){return (function(){try{var v60=[];
return (function(){while (l42.value!==l9.value)(function(v61,v62){(function(){var v64=v62;
var v65=l51;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v67){switch(arguments.length-1){case 0:v67=l9.value;
;
default:break;
}var v66=l9.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v66=new internals.Cons(arguments[I+1],v66);
var v68=this;
return (function(){var OBJ=v64;
var TMP=OBJ[internals.xstring(v65)]=internals.lisp_to_js(v67);
return TMP===undefined?l9.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v56;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v70=v62;
var v71=l52;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v73){switch(arguments.length-1){case 0:v73=l9.value;
;
default:break;
}var v72=l9.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v72=new internals.Cons(arguments[I+1],v72);
var v74=this;
return (function(){var OBJ=v70;
var TMP=OBJ[internals.xstring(v71)]=internals.lisp_to_js(v73);
return TMP===undefined?l9.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=internals.symbolValue(l5);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
(function(){var v76=v62;
var v77=l53;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v79){switch(arguments.length-1){case 0:v79=l9.value;
;
default:break;
}var v78=l9.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v78=new internals.Cons(arguments[I+1],v78);
var v80=this;
return (function(){var OBJ=v76;
var TMP=OBJ[internals.xstring(v77)]=internals.lisp_to_js(v79);
return TMP===undefined?l9.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v57;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
internals.js_to_lisp(v61['open'](internals.lisp_to_js(l54),internals.lisp_to_js(l55),internals.lisp_to_js(l9.value)));
internals.js_to_lisp(v61['setRequestHeader'](internals.lisp_to_js(l56),internals.lisp_to_js(l57)));
internals.js_to_lisp(v61['send'](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l13)['JSON']['stringify'](internals.lisp_to_js(v62))))));
return l58.fvalue(internals.pv,internals.js_to_lisp((function(){var TMP=v61['status'];
return TMP===undefined?l9.value:TMP;
})()),200)!==l9.value?(function(){var v82=internals.js_to_lisp((function(){var TMP=v61['responseText'];
return TMP===undefined?l9.value:TMP;
})());
var v83=internals.js_to_lisp(internals.symbolValue(l13)['JSON']['parse'](internals.lisp_to_js(v82)));
return internals.js_to_lisp((function(){var TMP=v83['timeout'];
return TMP===undefined?l9.value:TMP;
})())!==l9.value?(v56=l59):(function(){var values=internals.mv;
throw new internals.BlockNLX(v60,internals.js_to_lisp((function(){var TMP=v83['value'];
return TMP===undefined?l9.value:TMP;
})()),'NIL');
})();
})():l26.fvalue(internals.pv,l60);
})(l50.fvalue(internals.pv,internals.js_to_lisp((function(){var TMP=internals.symbolValue(l13)['XMLHttpRequest'];
return TMP===undefined?l9.value:TMP;
})())),{});
return l9.value;
})();
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v60) return values.apply(this,internals.forcemv(CF.values));
 else throw CF;
}})();
})();
});
FUNC.fname='SW-REQUEST-SYNC';
return FUNC;
})();
l49;
var l61=internals.intern('SLEEP');
var l62=internals.make_lisp_string('seconds');
var l63=internals.make_lisp_string('sleep');
l61.fvalue=(function(){var FUNC=(function JSCL_USER_SLEEP(values,v84){internals.checkArgs(arguments.length-1,1);
var v85=this;
return (function(){return (function(v87){(function(){var v89=v87;
var v90=l62;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v92){switch(arguments.length-1){case 0:v92=l9.value;
;
default:break;
}var v91=l9.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v91=new internals.Cons(arguments[I+1],v91);
var v93=this;
return (function(){var OBJ=v89;
var TMP=OBJ[internals.xstring(v90)]=internals.lisp_to_js(v92);
return TMP===undefined?l9.value:TMP;
})();
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v84;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return l49.fvalue(values,l63,v87);
})({});
})();
});
FUNC.fname='SLEEP';
return FUNC;
})();
l61;
var l64=internals.intern('*STDIN-BUFFER*','JSCL');
var l65=internals.make_lisp_string('');
if ((l64.value!==undefined?l42.value:l9.value)!==l9.value) l9.value;
 else l64.value=l65;
l64;
var l66=internals.intern('READ-STDIN','JSCL');
var l67=internals.make_lisp_string('readStdin');
l66.fvalue=(function(){var FUNC=(function JSCL_USER_READSTDIN(values){internals.checkArgsAtMost(arguments.length-1,0);
var v94=this;
return (function(){return (function(v96){(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v99){switch(arguments.length-1){case 0:v99=l9.value;
;
default:break;
}var v98=l9.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v98=new internals.Cons(arguments[I+1],v98);
var v100=this;
return l64.value=v99;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l17.fvalue(values,internals.symbolValue(l64),v96);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return internals.symbolValue(l64);
})(l49.fvalue(internals.pv,l67));
})();
});
FUNC.fname='READ-STDIN';
return FUNC;
})();
l66;
var l68=internals.intern('CLEAR-BUFFER','JSCL');
l68.fvalue=(function(){var FUNC=(function JSCL_USER_CLEARBUFFER(values){internals.checkArgsAtMost(arguments.length-1,0);
var v101=this;
return (function(){return (function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v105){switch(arguments.length-1){case 0:v105=l9.value;
;
default:break;
}var v104=l9.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v104=new internals.Cons(arguments[I+1],v104);
var v106=this;
return l64.value=v105;
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=l65;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='CLEAR-BUFFER';
return FUNC;
})();
l68;
var l69=internals.intern('%PEEK-CHAR-STDIN','JSCL');
var l70=internals.intern('LENGTH');
var l71=internals.intern('NUMBER');
var l72=internals.intern('CHAR');
l69.fvalue=(function(){var FUNC=(function JSCL_USER_PEEKCHARSTDIN(values){var v107=l9.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v107=new internals.Cons(arguments[I+1],v107);
var v108=this;
return (function(){return (function(){var x1=l70.fvalue(internals.pv,internals.symbolValue(l64));
if (typeof x1!='number') internals.typeError(x1,l71);
return 0<x1?l42.value:l9.value;
})()!==l9.value?l72.fvalue(values,internals.symbolValue(l64),0):(l66.fvalue(internals.pv),(function(){var F=internals.symbolFunction(l69);
var ARGS=[values];
var TAIL=v107;
while (TAIL!=l9.value){ARGS.push(TAIL.$$jscl_car);
TAIL=TAIL.$$jscl_cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})());
})();
});
FUNC.fname='%PEEK-CHAR-STDIN';
return FUNC;
})();
l69;
var l73=internals.intern('%READ-CHAR-STDIN','JSCL');
var l74=internals.intern('SUBSEQ');
l73.fvalue=(function(){var FUNC=(function JSCL_USER_READCHARSTDIN(values){var v110=l9.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v110=new internals.Cons(arguments[I+1],v110);
var v111=this;
return (function(){return (function(v113){(function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v116){switch(arguments.length-1){case 0:v116=l9.value;
;
default:break;
}var v115=l9.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v115=new internals.Cons(arguments[I+1],v115);
var v117=this;
return l64.value=v116;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l74.fvalue(values,internals.symbolValue(l64),1);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
return v113;
})((function(){var F=internals.symbolFunction(l69);
var ARGS=[internals.pv];
var TAIL=v110;
while (TAIL!=l9.value){ARGS.push(TAIL.$$jscl_car);
TAIL=TAIL.$$jscl_cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})());
})();
});
FUNC.fname='%READ-CHAR-STDIN';
return FUNC;
})();
l73;
var l75=internals.intern('INITIALIZE-WEB-WORKER','JSCL');
var l76=internals.intern('*STANDARD-OUTPUT*');
var l77=internals.intern('WRITE-FN','KEYWORD');
l77.value=l77;
var l78=internals.intern('MAKE-STREAM','JSCL');
var l79=internals.make_lisp_string('jqconsole-error');
var l80=internals.intern('*STANDARD-INPUT*');
var l81=internals.intern('READ-CHAR-FN','KEYWORD');
l81.value=l81;
var l82=internals.intern('PEEK-CHAR-FN','KEYWORD');
l82.value=l82;
var l83=internals.intern('WELCOME-MESSAGE','JSCL');
var l84=internals.make_lisp_string('onmessage');
var l85=internals.make_lisp_string('init');
var l86=internals.intern('STRING=');
l75.fvalue=(function(){var FUNC=(function JSCL_USER_INITIALIZEWEBWORKER(values){internals.checkArgsAtMost(arguments.length-1,0);
var v118=this;
return (function(){l76.value=l78.fvalue(internals.pv,l77.value,internals.symbolFunction(l6));
l19.value=l78.fvalue(internals.pv,l77.value,(function JSCL_USER_NIL(values,v120){internals.checkArgs(arguments.length-1,1);
var v121=this;
return l6.fvalue(values,v120,l79);
}));
l38.value=internals.symbolValue(l76);
l80.value=l78.fvalue(internals.pv,l81.value,internals.symbolFunction(l73),l82.value,internals.symbolFunction(l69));
l83.fvalue(internals.pv);
return (function(){var v123=internals.symbolValue(l13);
var v124=l84;
return (function(){var FUNC=(function JSCL_USER_NIL(values,v126){switch(arguments.length-1){case 0:v126=l9.value;
;
default:break;
}var v125=l9.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v125=new internals.Cons(arguments[I+1],v125);
var v127=this;
return (function(){var OBJ=v123;
var TMP=OBJ[internals.xstring(v124)]=internals.lisp_to_js(v126);
return TMP===undefined?l9.value:TMP;
})();
});
var ARGS=[values];
return (function(){var values=internals.mv;
var VS;
VS=(function JSCL_USER_NIL(values,v128){internals.checkArgs(arguments.length-1,1);
var v129=this;
return (function(){var v131=internals.js_to_lisp((function(){var TMP=v128['data'];
return TMP===undefined?l9.value:TMP;
})());
var v132=internals.js_to_lisp((function(){var TMP=v131['command'];
return TMP===undefined?l9.value:TMP;
})());
var v133=internals.js_to_lisp((function(){var TMP=v131['sessionId'];
return TMP===undefined?l9.value:TMP;
})());
return l86.fvalue(internals.pv,v132,l85)!==l9.value?((function(){return (function(){var FUNC=(function JSCL_USER_NIL(values,v136){switch(arguments.length-1){case 0:v136=l9.value;
;
default:break;
}var v135=l9.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v135=new internals.Cons(arguments[I+1],v135);
var v137=this;
return l5.value=v136;
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=v133;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),l14.fvalue(values)):l9.value;
})();
});
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})();
})();
});
FUNC.fname='INITIALIZE-WEB-WORKER';
return FUNC;
})();
l75;
l75.fvalue(internals.pv);
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'):
typeof window !== 'undefined'? window.jscl: self.jscl )