if (typeof importScripts !== 'undefined') importScripts('./jscl.js');
(function(jscl){
'use strict';
(function(internals){ var values = internals.values;var l1=internals.intern('*PACKAGE*');
var l2=internals.intern('JSCL','KEYWORD');
l2.value=l2;
var l3=internals.intern('FIND-PACKAGE-OR-FAIL','JSCL');
l1.value=l3.fvalue(l2);
var l4=internals.make_lisp_string('loading worker.lisp!');
console.log(internals.xstring(l4));
var l5=internals.intern('*WEB-WORKER-SESSION-ID*','JSCL');
l5;
var l6=internals.intern('%WEB-WORKER-WRITE-STRING','JSCL');
var l7=internals.make_lisp_string('jqconsole-output');
var l8=internals.make_lisp_string('command');
var l9=internals.intern('NIL');
var l10=internals.make_lisp_string('stringclass');
var l11=internals.make_lisp_string('string');
var l12=internals.intern('*ROOT*','JSCL');
l6.fvalue=(function(){var FUNC=(function JSCL_USER_WEBWORKERWRITESTRING(v1,v2){internals.checkArgsAtLeast(arguments.length,1);
internals.checkArgsAtMost(arguments.length,2);
switch(arguments.length){case 1:v2=l7;
;
default:break;
}var v3=this;
return (function(){return (function(v5){(function(){var v7=v5;
var v8=l8;
return (function(){var FUNC=(function JSCL_USER_NIL(v10){switch(arguments.length){case 0:v10=l9.value;
;
default:break;
}var v9=l9.value;
var I;
for (I=arguments.length-1;I>=1;I--)v9=new internals.Cons(arguments[I],v9);
var v11=this;
return v7[internals.xstring(v8)]=v10;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1('output');
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
(function(){var v13=v5;
var v14=l10;
return (function(){var FUNC=(function JSCL_USER_NIL(v16){switch(arguments.length){case 0:v16=l9.value;
;
default:break;
}var v15=l9.value;
var I;
for (I=arguments.length-1;I>=1;I--)v15=new internals.Cons(arguments[I],v15);
var v17=this;
return v13[internals.xstring(v14)]=v16;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.xstring(v2);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
(function(){var v19=v5;
var v20=l11;
return (function(){var FUNC=(function JSCL_USER_NIL(v22){switch(arguments.length){case 0:v22=l9.value;
;
default:break;
}var v21=l9.value;
var I;
for (I=arguments.length-1;I>=1;I--)v21=new internals.Cons(arguments[I],v21);
var v23=this;
return v19[internals.xstring(v20)]=v22;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.xstring(v1);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
return internals.symbolValue(l12)['postMessage'](v5);
})({});
})();
});
FUNC.fname=internals.make_lisp_string('%WEB-WORKER-WRITE-STRING');
return FUNC;
})();
l6;
var l13=internals.intern('WEB-WORKER-REPL','JSCL');
var l14=internals.intern('PACKAGE-NAME-FOR-PROMPT','JSCL');
var l15=internals.make_lisp_string('> ');
var l16=internals.intern('CONCAT','JSCL');
var l17=internals.make_lisp_string('jqconsole-prompt');
var l18=internals.intern('T');
var l19=internals.intern('CLSTRING','JSCL');
var l20=internals.intern('*ERROR-OUTPUT*');
var l21=internals.intern('FORMAT-ERROR','JSCL');
var l22=internals.intern('COMPLAINT','KEYWORD');
l22.value=l22;
var l23=internals.make_lisp_string('Required argument missing');
var l24=internals.intern('CONTROL-STRING','KEYWORD');
l24.value=l24;
var l25=internals.make_lisp_string('ERROR[!]: ~a~%~A~%');
var l26=internals.intern('OFFSET','KEYWORD');
l26.value=l26;
var l27=internals.intern('ERROR');
var l28=internals.make_lisp_string('ERROR[!]: ');
var l29=internals.intern('WRITE-STRING');
var l30=internals.intern('PRINC');
var l31=internals.intern('TERPRI');
var l32=internals.make_lisp_string('');
var l33=internals.intern('CALL-FORMATTER','JSCL');
var l34=internals.intern('*HANDLER-BINDINGS*','JSCL');
var l35=internals.intern('SERIOUS-CONDITION');
var l36=internals.make_lisp_string('~A: ~A~%');
var l37=internals.make_lisp_string(': ');
var l38=internals.intern('CLASS-OF');
var l39=internals.intern('CLASS-NAME');
var l40=internals.intern('*TRACE-OUTPUT*');
var l41=internals.intern('FROM','KEYWORD');
l41.value=l41;
var l42=internals.intern('SIGNAL');
var l43=internals.intern('FORMAT-BACKTRACE','JSCL');
var l44=internals.intern('%%ERROR','JSCL');
var l45=internals.intern('LIST');
var l46=internals.intern('READ');
var l47=internals.intern('EVAL-INTERACTIVE','JSCL');
var l48=internals.intern('FRESH-LINE');
var l49=internals.intern('PRIN1');
l13.fvalue=(function(){var FUNC=(function JSCL_USER_WEBWORKERREPL(){internals.checkArgsAtMost(arguments.length,0);
var v24=this;
return (function(){return (function(){return (function(){var v27=1;
var v28=[];
TBLOOP:while (true){try{switch(v27){case 1:{l6.fvalue(l16.fvalue(l14.fvalue(internals.symbolValue(l1)),l15),l17);
(function(){try{return (function(){try{var v38=[];
return (function(v39){return internals.bindSpecialBindings([l34],[v39],(function(){(function(){var v41=new internals.Cons(l35,(function JSCL_USER_NIL(v42){internals.checkArgs(arguments.length,1);
var v43=this;
l33.fvalue(internals.symbolValue(l20),(function JSCL_USER_NIL(v45,v46,v47){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v46=l27.fvalue(l21,l22.value,l23,l24.value,l36,l26.value,1);
;
case 2:v47=l27.fvalue(l21,l22.value,l23,l24.value,l36,l26.value,5);
;
default:break;
}var v44=l9.value;
var I;
for (I=arguments.length-1;I>=3;I--)v44=new internals.Cons(arguments[I],v44);
var v48=this;
(function(){l30.fvalue(v46,v45);
l29.fvalue(l37,v45);
l30.fvalue(v47,v45);
return l31.fvalue(v45);
})();
return internals.values1(v44);
}),l39.fvalue(l38.fvalue(v42)),v42);
l43.fvalue(internals.symbolValue(l40),l41.value,internals.symbolFunction(l42));
return (function(){throw new internals.BlockNLX(v38,l9.value,null,'BAIL-OUT');
})();
}));
var v50=new internals.Cons(v41,internals.symbolValue(l34));
return l34.value=v50;
})();
return (function(){try{return (function(){return (function(v54,v55){(function(){while (v54!==l9.value){v55=v54.$$jscl_car;
l48.fvalue();
l49.fvalue(v55);
l31.fvalue();
l9.value;
v54=v54.$$jscl_cdr;
}return l9.value;
})();
return l9.value;
})((function(){var FUNC=internals.symbolFunction(l45);
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.mvcall(l47.fvalue,l46.fvalue());
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})(),l9.value);
})();
}catch (v51){return (internals.isNLX(v51)?l18.value:l9.value)!==l9.value?(function(){throw v51;
})():l44.fvalue((function(v52){return (v52===undefined?l18.value:l9.value)!==l9.value?l19.fvalue(v51):l19.fvalue(v52);
})(v51['message']));
}})();
}));
})(internals.symbolValue(l34));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v38) return CF.value;
 else throw CF;
}})();
}catch (v29){return (function(v31){return l33.fvalue(internals.symbolValue(l20),(function JSCL_USER_NIL(v33,v34,v35){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v34=l27.fvalue(l21,l22.value,l23,l24.value,l25,l26.value,11);
;
case 2:v35=l27.fvalue(l21,l22.value,l23,l24.value,l25,l26.value,15);
;
default:break;
}var v32=l9.value;
var I;
for (I=arguments.length-1;I>=3;I--)v32=new internals.Cons(arguments[I],v32);
var v36=this;
(function(){l29.fvalue(l28,v33);
l30.fvalue(v34,v33);
l31.fvalue(v33);
l30.fvalue(v35,v33);
return l31.fvalue(v33);
})();
return internals.values1(v32);
}),v31,l19.fvalue(v29['stack']??l32));
})((function(v30){return (v30===undefined?l18.value:l9.value)!==l9.value?l19.fvalue(v29):l19.fvalue(v30);
})(v29['message']));
}})();
}(function(){throw new internals.TagNLX(v28,1);
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v28) v27=JUMP.label;
 else throw JUMP;
}}return l9.value;
})();
})();
})();
});
FUNC.fname=internals.make_lisp_string('WEB-WORKER-REPL');
return FUNC;
})();
l13;
var l50=internals.intern('SW-REQUEST-SYNC','JSCL');
var l51=internals.make_lisp_string('command');
var l52=internals.make_lisp_string('sessionId');
var l53=internals.make_lisp_string('options');
var l54=internals.intern('EQL');
var l55=internals.make_lisp_string('wait');
var l56=internals.make_lisp_string('Could not contact with the service worker.');
l50.fvalue=(function(){var FUNC=(function JSCL_USER_SWREQUESTSYNC(v56,v57){internals.checkArgsAtLeast(arguments.length,1);
internals.checkArgsAtMost(arguments.length,2);
switch(arguments.length){case 1:v57={};
;
default:break;
}var v58=this;
return (function(){return (function(){try{var v60=[];
return (function(){while (l18.value!==l9.value)(function(v61,v62){(function(){var v64=v62;
var v65=l51;
return (function(){var FUNC=(function JSCL_USER_NIL(v67){switch(arguments.length){case 0:v67=l9.value;
;
default:break;
}var v66=l9.value;
var I;
for (I=arguments.length-1;I>=1;I--)v66=new internals.Cons(arguments[I],v66);
var v68=this;
return v64[internals.xstring(v65)]=v67;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.xstring(v56);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
(function(){var v70=v62;
var v71=l52;
return (function(){var FUNC=(function JSCL_USER_NIL(v73){switch(arguments.length){case 0:v73=l9.value;
;
default:break;
}var v72=l9.value;
var I;
for (I=arguments.length-1;I>=1;I--)v72=new internals.Cons(arguments[I],v72);
var v74=this;
return v70[internals.xstring(v71)]=v73;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.symbolValue(l5);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
(function(){var v76=v62;
var v77=l53;
return (function(){var FUNC=(function JSCL_USER_NIL(v79){switch(arguments.length){case 0:v79=l9.value;
;
default:break;
}var v78=l9.value;
var I;
for (I=arguments.length-1;I>=1;I--)v78=new internals.Cons(arguments[I],v78);
var v80=this;
return v76[internals.xstring(v77)]=v79;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1(v57);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
v61['open']('POST','__jscl',false);
v61['setRequestHeader']('ContentType','application/json');
v61['send'](internals.symbolValue(l12)['JSON']['stringify'](v62));
return l54.fvalue(v61['status'],200)!==l9.value?(function(){var v82=v61['responseText'];
var v83=internals.symbolValue(l12)['JSON']['parse'](v82);
return (('timeout' in v83?l18.value:l9.value)!==l9.value?v83['timeout']:l9.value)!==l9.value?(v56=l55):(function(){var _R=internals.withMV((function(){return v83['value'];
}));
throw new internals.BlockNLX(v60,_R.result,_R.mv,'NIL');
})();
})():internals.mvcall(l27.fvalue,l56);
})(internals.newInstance(internals.symbolValue(l12)['XMLHttpRequest']),{});
return l9.value;
})();
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v60) {internals._mv=CF.mv;
return CF.value;
} else throw CF;
}})();
})();
});
FUNC.fname=internals.make_lisp_string('SW-REQUEST-SYNC');
return FUNC;
})();
l50;
var l57=internals.intern('SLEEP');
var l58=internals.make_lisp_string('seconds');
var l59=internals.make_lisp_string('sleep');
l57.fvalue=(function(){var FUNC=(function JSCL_USER_SLEEP(v84){internals.checkArgs(arguments.length,1);
var v85=this;
return (function(){return (function(v87){(function(){var v89=v87;
var v90=l58;
return (function(){var FUNC=(function JSCL_USER_NIL(v92){switch(arguments.length){case 0:v92=l9.value;
;
default:break;
}var v91=l9.value;
var I;
for (I=arguments.length-1;I>=1;I--)v91=new internals.Cons(arguments[I],v91);
var v93=this;
return v89[internals.xstring(v90)]=v92;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1(v84);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
l50.fvalue(l59,v87);
return internals.values1(l9.value);
})({});
})();
});
FUNC.fname=internals.make_lisp_string('SLEEP');
return FUNC;
})();
l57;
var l60=internals.intern('*STDIN-BUFFER*','JSCL');
if ((l60.value!==internals.UNBOUND?l18.value:l9.value)!==l9.value) l9.value;
 else l60.value=l32;
l60;
var l61=internals.intern('READ-STDIN','JSCL');
var l62=internals.make_lisp_string('readStdin');
l61.fvalue=(function(){var FUNC=(function JSCL_USER_READSTDIN(){internals.checkArgsAtMost(arguments.length,0);
var v94=this;
return (function(){return (function(v96){(function(){return (function(){var FUNC=(function JSCL_USER_NIL(v99){switch(arguments.length){case 0:v99=l9.value;
;
default:break;
}var v98=l9.value;
var I;
for (I=arguments.length-1;I>=1;I--)v98=new internals.Cons(arguments[I],v98);
var v100=this;
return l60.value=v99;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.mvcall(l16.fvalue,internals.symbolValue(l60),v96);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
return internals.symbolValue(l60);
})(l19.fvalue(l50.fvalue(l62)));
})();
});
FUNC.fname=internals.make_lisp_string('READ-STDIN');
return FUNC;
})();
l61;
var l63=internals.intern('CLEAR-BUFFER','JSCL');
l63.fvalue=(function(){var FUNC=(function JSCL_USER_CLEARBUFFER(){internals.checkArgsAtMost(arguments.length,0);
var v101=this;
return (function(){return (function(){return (function(){var FUNC=(function JSCL_USER_NIL(v105){switch(arguments.length){case 0:v105=l9.value;
;
default:break;
}var v104=l9.value;
var I;
for (I=arguments.length-1;I>=1;I--)v104=new internals.Cons(arguments[I],v104);
var v106=this;
return l60.value=v105;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1(l32);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
})();
});
FUNC.fname=internals.make_lisp_string('CLEAR-BUFFER');
return FUNC;
})();
l63;
var l64=internals.intern('%PEEK-CHAR-STDIN','JSCL');
var l65=internals.intern('LENGTH');
var l66=internals.intern('NUMBER');
var l67=internals.intern('CHAR');
l64.fvalue=(function(){var FUNC=(function JSCL_USER_PEEKCHARSTDIN(){var v107=l9.value;
var I;
for (I=arguments.length-1;I>=0;I--)v107=new internals.Cons(arguments[I],v107);
var v108=this;
return (function(){return (function(){var x1=l65.fvalue(internals.symbolValue(l60));
if (typeof x1!='number') internals.typeError(x1,l66);
return 0<x1?l18.value:l9.value;
})()!==l9.value?internals.mvcall(l67.fvalue,internals.symbolValue(l60),0):(l61.fvalue(),(function(){var F=internals.symbolFunction(l64);
var ARGS=[];
var TAIL=v107;
while (TAIL!=l9.value){ARGS.push(TAIL.$$jscl_car);
TAIL=TAIL.$$jscl_cdr;
}return internals.mvcall(typeof F==='function'?F:F.fvalue,...ARGS);
})());
})();
});
FUNC.fname=internals.make_lisp_string('%PEEK-CHAR-STDIN');
return FUNC;
})();
l64;
var l68=internals.intern('%READ-CHAR-STDIN','JSCL');
var l69=internals.intern('SUBSEQ');
l68.fvalue=(function(){var FUNC=(function JSCL_USER_READCHARSTDIN(){var v110=l9.value;
var I;
for (I=arguments.length-1;I>=0;I--)v110=new internals.Cons(arguments[I],v110);
var v111=this;
return (function(){return (function(v113){(function(){return (function(){var FUNC=(function JSCL_USER_NIL(v116){switch(arguments.length){case 0:v116=l9.value;
;
default:break;
}var v115=l9.value;
var I;
for (I=arguments.length-1;I>=1;I--)v115=new internals.Cons(arguments[I],v115);
var v117=this;
return l60.value=v116;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.mvcall(l69.fvalue,internals.symbolValue(l60),1);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
return internals.values1(v113);
})((function(){var F=internals.symbolFunction(l64);
var ARGS=[];
var TAIL=v110;
while (TAIL!=l9.value){ARGS.push(TAIL.$$jscl_car);
TAIL=TAIL.$$jscl_cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})());
})();
});
FUNC.fname=internals.make_lisp_string('%READ-CHAR-STDIN');
return FUNC;
})();
l68;
var l70=internals.intern('INITIALIZE-WEB-WORKER','JSCL');
var l71=internals.intern('*STANDARD-OUTPUT*');
var l72=internals.intern('WRITE-FN','KEYWORD');
l72.value=l72;
var l73=internals.intern('MAKE-STREAM','JSCL');
var l74=internals.make_lisp_string('jqconsole-error');
var l75=internals.intern('*STANDARD-INPUT*');
var l76=internals.intern('READ-CHAR-FN','KEYWORD');
l76.value=l76;
var l77=internals.intern('PEEK-CHAR-FN','KEYWORD');
l77.value=l77;
var l78=internals.intern('WELCOME-MESSAGE','JSCL');
var l79=internals.make_lisp_string('onmessage');
var l80=internals.make_lisp_string('init');
var l81=internals.intern('STRING=');
l70.fvalue=(function(){var FUNC=(function JSCL_USER_INITIALIZEWEBWORKER(){internals.checkArgsAtMost(arguments.length,0);
var v118=this;
return (function(){l71.value=l73.fvalue(l72.value,internals.symbolFunction(l6));
l20.value=l73.fvalue(l72.value,(function JSCL_USER_NIL(v120){internals.checkArgs(arguments.length,1);
var v121=this;
return internals.mvcall(l6.fvalue,v120,l74);
}));
l40.value=internals.symbolValue(l71);
l75.value=l73.fvalue(l76.value,internals.symbolFunction(l68),l77.value,internals.symbolFunction(l64));
l78.fvalue();
return (function(){var v123=internals.symbolValue(l12);
var v124=l79;
return (function(){var FUNC=(function JSCL_USER_NIL(v126){switch(arguments.length){case 0:v126=l9.value;
;
default:break;
}var v125=l9.value;
var I;
for (I=arguments.length-1;I>=1;I--)v125=new internals.Cons(arguments[I],v125);
var v127=this;
return v123[internals.xstring(v124)]=v126;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return (function JSCL_USER_NIL(v128){internals.checkArgs(arguments.length,1);
var v129=this;
return (function(){var v131=v128['data'];
var v132=l19.fvalue(v131['command']);
var v133=v131['sessionId'];
return l81.fvalue(v132,l80)!==l9.value?((function(){return (function(){var FUNC=(function JSCL_USER_NIL(v136){switch(arguments.length){case 0:v136=l9.value;
;
default:break;
}var v135=l9.value;
var I;
for (I=arguments.length-1;I>=1;I--)v135=new internals.Cons(arguments[I],v135);
var v137=this;
return l5.value=v136;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1(v133);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})(),internals.mvcall(l13.fvalue)):internals.values1(l9.value);
})();
});
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
})();
});
FUNC.fname=internals.make_lisp_string('INITIALIZE-WEB-WORKER');
return FUNC;
})();
l70;
l70.fvalue();
})(jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'):
typeof window !== 'undefined'? window.jscl: self.jscl )