(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.make_lisp_string('loading repl-web/repl.lisp!');
console.log(internals.xstring(l1));
var l2=internals.intern('%WRITE-STRING');
var l3=internals.intern('T','COMMON-LISP');
var l4=internals.make_lisp_string('jqconsole-output');
var l5=internals.intern('*ROOT*');
var l6=internals.make_lisp_string('jqconsole');
var l7=internals.intern('NIL','COMMON-LISP');
var l8=internals.make_lisp_string('jqconsole');
var l9=internals.make_lisp_string('Write');
var l10=internals.make_lisp_string('');
var l11=internals.make_lisp_string('jqconsole');
var l12=internals.make_lisp_string('Write');
var l13=internals.make_lisp_string('console');
var l14=internals.make_lisp_string('log');
l2.fvalue=(function(){var FUNC=(function JSCL_USER_WRITESTRING(values,v1,v2,v3){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 1:v2=l3.value;
;
case 2:v3=l4;
;
default:break;
}var v4=this;
return (function(){return internals.js_to_lisp((function(){var TMP=internals.symbolValue(l5)[internals.xstring(l6)];
return TMP===undefined?l7.value:TMP;
})())!==l7.value?v2!==l7.value?internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l8)][internals.xstring(l9)](internals.lisp_to_js(v1),internals.lisp_to_js(v3))):internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l11)][internals.xstring(l12)](internals.lisp_to_js(v1),internals.lisp_to_js(v3),internals.lisp_to_js(l10))):internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l13)][internals.xstring(l14)](internals.lisp_to_js(v1)));
})();
});
FUNC.fname='%WRITE-STRING';
return FUNC;
})();
l2;
var l15=internals.intern('LOAD-HISTORY');
var l16=internals.make_lisp_string('jqhist');
var l17=internals.make_lisp_string('localStorage');
var l18=internals.make_lisp_string('getItem');
var l19=internals.make_lisp_string('JSON');
var l20=internals.make_lisp_string('parse');
var l21=internals.make_lisp_string('jqconsole');
var l22=internals.make_lisp_string('SetHistory');
l15.fvalue=(function(){var FUNC=(function JSCL_USER_LOADHISTORY(values){internals.checkArgsAtMost(arguments.length-1,0);
var v6=this;
return (function(){return (function(v8){return (v8===null?l3.value:l7.value)!==l7.value?l7.value:internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l21)][internals.xstring(l22)](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l19)][internals.xstring(l20)](internals.lisp_to_js(v8))))));
})(internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l17)][internals.xstring(l18)](internals.lisp_to_js(l16))));
})();
});
FUNC.fname='LOAD-HISTORY';
return FUNC;
})();
l15;
var l23=internals.intern('SAVE-HISTORY');
var l24=internals.make_lisp_string('jqhist');
var l25=internals.make_lisp_string('jqconsole');
var l26=internals.make_lisp_string('GetHistory');
var l27=internals.make_lisp_string('JSON');
var l28=internals.make_lisp_string('stringify');
var l29=internals.make_lisp_string('localStorage');
var l30=internals.make_lisp_string('setItem');
l23.fvalue=(function(){var FUNC=(function JSCL_USER_SAVEHISTORY(values){internals.checkArgsAtMost(arguments.length-1,0);
var v9=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l29)][internals.xstring(l30)](internals.lisp_to_js(l24),internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l27)][internals.xstring(l28)](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l25)][internals.xstring(l26)]())))))));
})();
});
FUNC.fname='SAVE-HISTORY';
return FUNC;
})();
l23;
var l31=internals.intern('%MAP-JS-OBJECT');
var l32=internals.intern('LIST','COMMON-LISP');
var l33=internals.make_lisp_string('Object');
var l34=internals.make_lisp_string('keys');
var l35=internals.intern('VECTOR-TO-LIST');
var l36=internals.intern('MAPCAR','COMMON-LISP');
l31.fvalue=(function(){var FUNC=(function JSCL_USER_MAPJSOBJECT(values,v11){internals.checkArgs(arguments.length-1,1);
var v12=this;
return (function(){return l36.fvalue(values,(function JSCL_USER_NIL(values,v14){internals.checkArgs(arguments.length-1,1);
var v15=this;
return l32.fvalue(values,v14,internals.js_to_lisp((function(){var TMP=v11[internals.xstring(v14)];
return TMP===undefined?l7.value:TMP;
})()));
}),l36.fvalue(internals.pv,(function JSCL_USER_NIL(values,v16){internals.checkArgs(arguments.length-1,1);
var v17=this;
return internals.js_to_lisp(v16);
}),l35.fvalue(internals.pv,internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l33)][internals.xstring(l34)](internals.lisp_to_js(v11))))));
})();
});
FUNC.fname='%MAP-JS-OBJECT';
return FUNC;
})();
l31;
var l37=internals.intern('%CONSOLE-TERPRI');
var l38=internals.intern('STRING','COMMON-LISP');
var l39=internals.make_lisp_string('jqconsole-error');
var l40=internals.make_lisp_string('jqconsole');
var l41=internals.make_lisp_string('Write');
l37.fvalue=(function(){var FUNC=(function JSCL_USER_CONSOLETERPRI(values){internals.checkArgsAtMost(arguments.length-1,0);
var v18=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l40)][internals.xstring(l41)](internals.lisp_to_js(l38.fvalue(internals.pv,'\n')),internals.lisp_to_js(l39)));
})();
});
FUNC.fname='%CONSOLE-TERPRI';
return FUNC;
})();
l37;
var l42=internals.intern('ERRMSG-PREFIX');
var l43=internals.make_lisp_string('ERROR: ');
var l44=internals.make_lisp_string('jqconsole-error');
var l45=internals.make_lisp_string('jqconsole');
var l46=internals.make_lisp_string('Write');
l42.fvalue=(function(){var FUNC=(function JSCL_USER_ERRMSGPREFIX(values){internals.checkArgsAtMost(arguments.length-1,0);
var v20=this;
return (function(){return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l45)][internals.xstring(l46)](internals.lisp_to_js(l43),internals.lisp_to_js(l44)));
})();
});
FUNC.fname='ERRMSG-PREFIX';
return FUNC;
})();
l42;
var l47=internals.intern('+ERR-CSS+');
var l48=internals.make_lisp_string('jqconsole-error');
l47.value=l48;
l47;
var l49=internals.intern('DISPLAY-CONDITION');
var l50=internals.intern('FORMAT-ERROR');
var l51=internals.intern('COMPLAINT','KEYWORD');
l51.value=l51;
var l52=internals.make_lisp_string('Required argument missing');
var l53=internals.intern('CONTROL-STRING','KEYWORD');
l53.value=l53;
var l54=internals.make_lisp_string('~A: ~A');
var l55=internals.intern('OFFSET','KEYWORD');
l55.value=l55;
var l56=internals.intern('ERROR','COMMON-LISP');
var l57=internals.intern('PRINC','COMMON-LISP');
var l58=internals.make_lisp_string(': ');
var l59=internals.intern('WRITE-STRING','COMMON-LISP');
var l60=internals.intern('CLASS-OF','COMMON-LISP');
var l61=internals.intern('CLASS-NAME','COMMON-LISP');
var l62=internals.intern('CALL-FORMATTER');
var l63=internals.make_lisp_string('jqconsole');
var l64=internals.make_lisp_string('Write');
var l65=internals.make_lisp_string(': ');
l49.fvalue=(function(){var FUNC=(function JSCL_USER_DISPLAYCONDITION(values,v22,v23,v24){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,3);
switch(arguments.length-1){case 1:v23=internals.symbolValue(l47);
;
case 2:v24=l3.value;
;
default:break;
}var v25=this;
return (function(){internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l63)][internals.xstring(l64)](internals.lisp_to_js(l62.fvalue(internals.pv,l7.value,(function JSCL_USER_NIL(values,v34,v35,v36){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v35=l56.fvalue(internals.pv,l50,l51.value,l52,l53.value,l54,l55.value,1);
;
case 2:v36=l56.fvalue(internals.pv,l50,l51.value,l52,l53.value,l54,l55.value,5);
;
default:break;
}var v33=l7.value;
var I;
for (I=arguments.length-1-1;I>=3;I--)v33=new internals.Cons(arguments[I+1],v33);
var v37=this;
(function(){l57.fvalue(internals.pv,v35,v34);
l59.fvalue(internals.pv,l65,v34);
return l57.fvalue(internals.pv,v36,v34);
})();
return v33;
}),l61.fvalue(internals.pv,l60.fvalue(internals.pv,v22)),v22)),internals.lisp_to_js(v23)));
return v24!==l7.value?l37.fvalue(values):l7.value;
})();
});
FUNC.fname='DISPLAY-CONDITION';
return FUNC;
})();
l49;
var l66=internals.intern('TOPLEVEL');
var l67=internals.make_lisp_string('(');
var l68=internals.make_lisp_string(')');
var l69=internals.make_lisp_string('parents');
var l70=internals.make_lisp_string('jqconsole');
var l71=internals.make_lisp_string('RegisterMatching');
var l72=internals.make_lisp_string('~a> ');
var l73=internals.make_lisp_string('> ');
var l74=internals.intern('*PACKAGE*','COMMON-LISP');
var l75=internals.intern('PACKAGE-NAME-FOR-PROMPT');
var l76=internals.make_lisp_string('jqconsole-prompt');
var l77=internals.make_lisp_string('jqconsole');
var l78=internals.make_lisp_string('Write');
var l79=internals.make_lisp_string('console');
var l80=internals.make_lisp_string('log');
var l81=internals.make_lisp_string('message');
var l82=internals.make_lisp_string('ERROR[!]: ~a~%');
var l83=internals.make_lisp_string('ERROR[!]: ');
var l84=internals.intern('TERPRI','COMMON-LISP');
var l85=internals.make_lisp_string('jqconsole-error');
var l86=internals.make_lisp_string('jqconsole');
var l87=internals.make_lisp_string('Write');
var l88=internals.make_lisp_string('ERROR[!]: ');
var l89=internals.intern('*HANDLER-BINDINGS*');
var l90=internals.make_lisp_string('message');
var l91=internals.intern('%%ERROR');
var l92=internals.intern('LENGTH','COMMON-LISP');
var l93=internals.intern('READ-FROM-STRING','COMMON-LISP');
var l94=internals.intern('EVAL-INTERACTIVE');
var l95=internals.make_lisp_string('jqconsole');
var l96=internals.make_lisp_string('GetColumn');
var l97=internals.intern('ZEROP','COMMON-LISP');
var l98=internals.make_lisp_string('jqconsole-return');
var l99=internals.make_lisp_string('jqconsole');
var l100=internals.make_lisp_string('Write');
var l101=internals.make_lisp_string('~S~%');
var l102=internals.intern('PRIN1','COMMON-LISP');
var l103=internals.make_lisp_string('jqconsole-return');
var l104=internals.make_lisp_string('jqconsole');
var l105=internals.make_lisp_string('Write');
var l106=internals.intern('%SEXPR-INCOMPLETE');
var l107=internals.make_lisp_string('jqconsole');
var l108=internals.make_lisp_string('Prompt');
l66.fvalue=(function(){var FUNC=(function JSCL_USER_TOPLEVEL(values){internals.checkArgsAtMost(arguments.length-1,0);
var v39=this;
return (function(){internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l70)][internals.xstring(l71)](internals.lisp_to_js(l67),internals.lisp_to_js(l68),internals.lisp_to_js(l69)));
(function(v46){return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l77)][internals.xstring(l78)](internals.lisp_to_js(v46),internals.lisp_to_js(l76)));
})(l62.fvalue(internals.pv,l7.value,(function JSCL_USER_NIL(values,v42,v43){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v43=l56.fvalue(internals.pv,l50,l51.value,l52,l53.value,l72,l55.value,1);
;
default:break;
}var v41=l7.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v41=new internals.Cons(arguments[I+1],v41);
var v44=this;
(function(){l57.fvalue(internals.pv,v43,v42);
return l59.fvalue(internals.pv,l73,v42);
})();
return v41;
}),l75.fvalue(internals.pv,internals.symbolValue(l74))));
return (function(v93){return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l107)][internals.xstring(l108)](internals.lisp_to_js(l3.value),internals.lisp_to_js(v93),internals.lisp_to_js(internals.symbolFunction(l106))));
})((function JSCL_USER_NIL(values,v47){internals.checkArgs(arguments.length-1,1);
var v48=this;
return (function(){(function(){try{return (function(){try{var v64=[];
return (function(v65){return (function(){var v66=1;
var v67=[];
TBLOOP:while (true){try{switch(v66){case 1:(function(v68){return internals.bindSpecialBindings([l89],[v68],(function(){(function(){var v70=new internals.Cons(l56,(function JSCL_USER_NIL(values,v71){internals.checkArgs(arguments.length-1,1);
var v72=this;
v65=v71;
return (function(){throw new internals.TagNLX(v67,2);
})();
}));
var v73=new internals.Cons(v70,internals.symbolValue(l89));
return l89.value=v73;
})();
return (function(){try{return (function(){throw new internals.BlockNLX(v64,(function(){var x1=l92.fvalue(internals.pv,v47);
if (typeof x1!='number') throw 'Not a number!';
return x1>0?l3.value:l7.value;
})()!==l7.value?(function(){var v77=l93.fvalue(internals.pv,v47);
var v78=(function(){var FUNC=internals.symbolFunction(l32);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l94.fvalue(values,v77);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
return (function(){return (function(v80,v81){(function(){while (v80!==l7.value){v81=internals.car(v80);
if (l97.fvalue(internals.pv,internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l95)][internals.xstring(l96)]()))!==l7.value) l7.value;
 else internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l99)][internals.xstring(l100)](internals.lisp_to_js('\n'),internals.lisp_to_js(l98)));
internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l104)][internals.xstring(l105)](internals.lisp_to_js(l62.fvalue(internals.pv,l7.value,(function JSCL_USER_NIL(values,v88,v89){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v89=l56.fvalue(internals.pv,l50,l51.value,l52,l53.value,l101,l55.value,1);
;
default:break;
}var v87=l7.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v87=new internals.Cons(arguments[I+1],v87);
var v90=this;
(function(){l102.fvalue(internals.pv,v89,v88);
return l84.fvalue(internals.pv,v88);
})();
return v87;
}),v81)),internals.lisp_to_js(l103)));
l7.value;
v80=internals.cdr(v80);
}return l7.value;
})();
return l7.value;
})(v78,l7.value);
})();
})():l7.value,'G279');
})();
}catch (v74){v74=internals.js_to_lisp(v74);
return (internals.isNLX(v74)?l3.value:l7.value)!==l7.value?(function(){throw v74;
})():l91.fvalue(internals.pv,(function(v75){return v75!==l7.value?v75:v74;
})(internals.js_to_lisp((function(){var TMP=v74[internals.xstring(l90)];
return TMP===undefined?l7.value:TMP;
})())));
}})();
}));
})(internals.symbolValue(l89));
case 2:(function(){throw new internals.BlockNLX(v64,(function(v92){return l49.fvalue(internals.pv,v92);
})(v65),'G279');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v67) v66=JUMP.label;
 else throw JUMP;
}}return l7.value;
})();
})(l7.value);
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v64) return CF.values;
 else throw CF;
}})();
}catch (v50){v50=internals.js_to_lisp(v50);
internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l79)][internals.xstring(l80)](internals.lisp_to_js(v50)));
return (function(v53){return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l86)][internals.xstring(l87)](internals.lisp_to_js(l62.fvalue(internals.pv,l7.value,(function JSCL_USER_NIL(values,v60,v61){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v61=l56.fvalue(internals.pv,l50,l51.value,l52,l53.value,l82,l55.value,11);
;
default:break;
}var v59=l7.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v59=new internals.Cons(arguments[I+1],v59);
var v62=this;
(function(){l59.fvalue(internals.pv,l88,v60);
l57.fvalue(internals.pv,v61,v60);
return l84.fvalue(internals.pv,v60);
})();
return v59;
}),v53)),internals.lisp_to_js(l85)));
})((function(v51){return v51!==l7.value?v51:(function(v52){return v52!==l7.value?v52:v50;
})(l31.fvalue(internals.pv,v50));
})(internals.js_to_lisp((function(){var TMP=v50[internals.xstring(l81)];
return TMP===undefined?l7.value:TMP;
})())));
}})();
l23.fvalue(internals.pv);
return l66.fvalue(values);
})();
}));
})();
});
FUNC.fname='TOPLEVEL';
return FUNC;
})();
l66;
var l109=internals.intern('WEB-INIT');
var l110=internals.intern('*STANDARD-OUTPUT*','COMMON-LISP');
var l111=internals.intern('WRITE-FN','KEYWORD');
l111.value=l111;
var l112=internals.intern('MAKE-STREAM');
var l113=internals.intern('*ERROR-OUTPUT*','COMMON-LISP');
var l114=internals.make_lisp_string('jqconsole-error');
var l115=internals.intern('*TRACE-OUTPUT*','COMMON-LISP');
var l116=internals.intern('HTML','KEYWORD');
l116.value=l116;
var l117=internals.intern('WELCOME-MESSAGE');
var l118=internals.make_lisp_string('load');
var l119=internals.make_lisp_string('window');
var l120=internals.make_lisp_string('addEventListener');
l109.fvalue=(function(){var FUNC=(function JSCL_USER_WEBINIT(values){internals.checkArgsAtMost(arguments.length-1,0);
var v94=this;
return (function(){l15.fvalue(internals.pv);
l110.value=l112.fvalue(internals.pv,l111.value,(function JSCL_USER_NIL(values,v96){internals.checkArgs(arguments.length-1,1);
var v97=this;
return l2.fvalue(values,v96);
}));
l113.value=l112.fvalue(internals.pv,l111.value,(function JSCL_USER_NIL(values,v98){internals.checkArgs(arguments.length-1,1);
var v99=this;
return l2.fvalue(values,v98,l3.value,l114);
}));
l115.value=internals.symbolValue(l110);
l117.fvalue(internals.pv,l116.value,l3.value);
return internals.js_to_lisp(internals.symbolValue(l5)[internals.xstring(l119)][internals.xstring(l120)](internals.lisp_to_js(l118),internals.lisp_to_js((function JSCL_USER_NIL(values){var v102=l7.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v102=new internals.Cons(arguments[I+1],v102);
var v103=this;
return l66.fvalue(values);
}))));
})();
});
FUNC.fname='WEB-INIT';
return FUNC;
})();
l109;
l109.fvalue(internals.pv);
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
