#!/usr/bin/env node
if (typeof importScripts !== 'undefined') importScripts('./jscl.js');
(function(jscl){
'use strict';
(function(values, internals){var l1=internals.make_lisp_string('loading repl-node/repl.lisp!');
console.log(internals.xstring(l1));
var l2=internals.intern('*REPL*','JSCL');
l2;
var l3=internals.intern('START-REPL','JSCL');
var l4=internals.intern('WELCOME-MESSAGE','JSCL');
var l5=internals.intern('*PACKAGE*');
var l6=internals.intern('PACKAGE-NAME-FOR-PROMPT','JSCL');
var l7=internals.make_lisp_string('> ');
var l8=internals.intern('CONCAT','JSCL');
var l9=internals.intern('NSUBSTITUTE');
var l10=internals.intern('%SEXPR-INCOMPLETE','JSCL');
var l11=internals.intern('NIL');
var l12=internals.intern('*ROOT*','JSCL');
var l13=internals.intern('MAKE-NEW','JSCL');
var l14=internals.intern('*ERROR-OUTPUT*');
var l15=internals.intern('FORMAT-ERROR','JSCL');
var l16=internals.intern('COMPLAINT','KEYWORD');
l16.value=l16;
var l17=internals.make_lisp_string('Required argument missing');
var l18=internals.intern('CONTROL-STRING','KEYWORD');
l18.value=l18;
var l19=internals.make_lisp_string('ERROR[!]: ~a~%~A~%');
var l20=internals.intern('OFFSET','KEYWORD');
l20.value=l20;
var l21=internals.intern('ERROR');
var l22=internals.make_lisp_string('ERROR[!]: ');
var l23=internals.intern('WRITE-STRING');
var l24=internals.intern('PRINC');
var l25=internals.intern('TERPRI');
var l26=internals.intern('CALL-FORMATTER','JSCL');
var l27=internals.intern('*HANDLER-BINDINGS*','JSCL');
var l28=internals.intern('SERIOUS-CONDITION');
var l29=internals.make_lisp_string('~A: ~A~%');
var l30=internals.make_lisp_string(': ');
var l31=internals.intern('CLASS-OF');
var l32=internals.intern('CLASS-NAME');
var l33=internals.intern('*TRACE-OUTPUT*');
var l34=internals.intern('FROM','KEYWORD');
l34.value=l34;
var l35=internals.intern('SIGNAL');
var l36=internals.intern('FORMAT-BACKTRACE','JSCL');
var l37=internals.intern('T');
var l38=internals.intern('%%ERROR','JSCL');
var l39=internals.intern('LIST');
var l40=internals.intern('EVAL-INTERACTIVE-INPUT','JSCL');
var l41=internals.intern('FRESH-LINE');
var l42=internals.intern('PRIN1');
var l43=internals.make_lisp_string('');
var l44=internals.intern('CONSTANTLY');
l3.fvalue=(function(){var FUNC=(function JSCL_USER_STARTREPL(values){internals.checkArgsAtMost(arguments.length-1,0);
var v1=this;
return (function(){l4.fvalue(internals.pv);
return (function(){var v3=(function JSCL_USER_NIL(values){internals.checkArgsAtMost(arguments.length-1,0);
var v5=this;
return (function(){return l8.fvalue(values,l6.fvalue(internals.pv,internals.symbolValue(l5)),l7);
})();
});
var v4=(function JSCL_USER_NIL(values,v7,v8,v9,v10){internals.checkArgs(arguments.length-1,4);
var v11=this;
return (function(){v7=l9.fvalue(internals.pv,internals.char_from_codepoint(10),internals.char_from_codepoint(13),v7);
return l10.fvalue(internals.pv,v7)!==l11.value?(function(){var F=v10;
return (typeof F==='function'?F:F.fvalue)(values,l13.fvalue(internals.pv,internals.js_to_lisp((function(){var TMP=internals.symbolValue(l12)['repl'];
if (TMP===undefined) return l11.value;
TMP=TMP['Recoverable'];
return TMP===undefined?l11.value:TMP;
})())));
})():((function(){try{return (function(){try{var v22=[];
return (function(v23){return internals.bindSpecialBindings([l27],[v23],(function(){(function(){var v25=new internals.Cons(l28,(function JSCL_USER_NIL(values,v26){internals.checkArgs(arguments.length-1,1);
var v27=this;
l26.fvalue(internals.pv,internals.symbolValue(l14),(function JSCL_USER_NIL(values,v29,v30,v31){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v30=l21.fvalue(internals.pv,l15,l16.value,l17,l18.value,l29,l20.value,1);
;
case 2:v31=l21.fvalue(internals.pv,l15,l16.value,l17,l18.value,l29,l20.value,5);
;
default:break;
}var v28=l11.value;
var I;
for (I=arguments.length-1-1;I>=3;I--)v28=new internals.Cons(arguments[I+1],v28);
var v32=this;
(function(){l24.fvalue(internals.pv,v30,v29);
l23.fvalue(internals.pv,l30,v29);
l24.fvalue(internals.pv,v31,v29);
return l25.fvalue(internals.pv,v29);
})();
return v28;
}),l32.fvalue(internals.pv,l31.fvalue(internals.pv,v26)),v26);
l36.fvalue(internals.pv,internals.symbolValue(l33),l34.value,internals.symbolFunction(l35));
return (function(){throw new internals.BlockNLX(v22,l11.value,'BAIL-OUT');
})();
}));
var v34=new internals.Cons(v25,internals.symbolValue(l27));
return l27.value=v34;
})();
return (function(){try{return (function(){return (function(v38,v39){(function(){while (v38!==l11.value){v39=v38.$$jscl_car;
l41.fvalue(internals.pv);
l42.fvalue(internals.pv,v39);
l25.fvalue(internals.pv);
l11.value;
v38=v38.$$jscl_cdr;
}return l11.value;
})();
return l11.value;
})((function(){var FUNC=internals.symbolFunction(l39);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l40.fvalue(values,v7);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})(),l11.value);
})();
}catch (v35){v35=internals.js_to_lisp(v35);
return (internals.isNLX(v35)?l37.value:l11.value)!==l11.value?(function(){throw v35;
})():l38.fvalue(internals.pv,(function(v36){return v36!==l11.value?v36:v35;
})(internals.js_to_lisp((function(){var TMP=v35['message'];
return TMP===undefined?l11.value:TMP;
})())));
}})();
}));
})(internals.symbolValue(l27));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v22) return CF.values;
 else throw CF;
}})();
}catch (v13){v13=internals.js_to_lisp(v13);
return (function(v15){return l26.fvalue(internals.pv,internals.symbolValue(l14),(function JSCL_USER_NIL(values,v17,v18,v19){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v18=l21.fvalue(internals.pv,l15,l16.value,l17,l18.value,l19,l20.value,11);
;
case 2:v19=l21.fvalue(internals.pv,l15,l16.value,l17,l18.value,l19,l20.value,15);
;
default:break;
}var v16=l11.value;
var I;
for (I=arguments.length-1-1;I>=3;I--)v16=new internals.Cons(arguments[I+1],v16);
var v20=this;
(function(){l23.fvalue(internals.pv,l22,v17);
l24.fvalue(internals.pv,v18,v17);
l25.fvalue(internals.pv,v17);
l24.fvalue(internals.pv,v19,v17);
return l25.fvalue(internals.pv,v17);
})();
return v16;
}),v15,internals.js_to_lisp((function(){var TMP=v13['stack'];
return TMP===undefined?l11.value:TMP;
})()));
})((function(v14){return v14!==l11.value?v14:v13;
})(internals.js_to_lisp((function(){var TMP=v13['message'];
return TMP===undefined?l11.value:TMP;
})())));
}})(),internals.js_to_lisp(internals.symbolValue(l2)['setPrompt'](internals.lisp_to_js(v3(internals.pv)))),(function(){var F=v10;
return (typeof F==='function'?F:F.fvalue)(values,l11.value);
})());
})();
});
return l2.value=internals.js_to_lisp(internals.symbolValue(l12)['repl']['start'](internals.lisp_to_js({input: internals.lisp_to_js(internals.js_to_lisp((function(){var TMP=internals.symbolValue(l12)['process'];
if (TMP===undefined) return l11.value;
TMP=TMP['stdin'];
return TMP===undefined?l11.value:TMP;
})())),output: internals.lisp_to_js(internals.js_to_lisp((function(){var TMP=internals.symbolValue(l12)['process'];
if (TMP===undefined) return l11.value;
TMP=TMP['stdout'];
return TMP===undefined?l11.value:TMP;
})())),eval: internals.lisp_to_js(v4),writer: internals.lisp_to_js(l44.fvalue(internals.pv,l43)),prompt: internals.lisp_to_js(v3(internals.pv))})));
})();
})();
});
FUNC.fname='START-REPL';
return FUNC;
})();
l3;
var l45=internals.intern('NODE-INIT','JSCL');
var l46=internals.intern('*STANDARD-OUTPUT*');
var l47=internals.intern('WRITE-FN','KEYWORD');
l47.value=l47;
var l48=internals.intern('MAKE-STREAM','JSCL');
var l49=internals.intern('JS-TO-LISP','JSCL');
var l50=internals.intern('SUBSEQ');
var l51=internals.intern('VECTOR-TO-LIST','JSCL');
var l52=internals.intern('MAPCAR');
var l53=internals.intern('NULL');
var l54=internals.intern('LOAD');
l45.fvalue=(function(){var FUNC=(function JSCL_USER_NODEINIT(values){internals.checkArgsAtMost(arguments.length-1,0);
var v40=this;
return (function(){l46.value=l48.fvalue(internals.pv,l47.value,(function JSCL_USER_NIL(values,v42){internals.checkArgs(arguments.length-1,1);
var v43=this;
return internals.js_to_lisp(internals.symbolValue(l12)['process']['stdout']['write'](internals.lisp_to_js(v42)));
}));
l14.value=internals.symbolValue(l46);
l33.value=internals.symbolValue(l46);
return (function(v44){return l53.fvalue(internals.pv,v44)!==l11.value?l3.fvalue(values):(function(){return (function(v46,v47){(function(){while (v46!==l11.value){v47=v46.$$jscl_car;
l54.fvalue(internals.pv,v47);
l11.value;
v46=v46.$$jscl_cdr;
}return l11.value;
})();
return l11.value;
})(v44,l11.value);
})();
})(l52.fvalue(internals.pv,internals.symbolFunction(l49),l51.fvalue(internals.pv,l50.fvalue(internals.pv,internals.js_to_lisp((function(){var TMP=internals.symbolValue(l12)['process'];
if (TMP===undefined) return l11.value;
TMP=TMP['argv'];
return TMP===undefined?l11.value:TMP;
})()),2))));
})();
});
FUNC.fname='NODE-INIT';
return FUNC;
})();
l45;
l45.fvalue(internals.pv);
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'):
typeof window !== 'undefined'? window.jscl: self.jscl )