if (typeof importScripts !== 'undefined') importScripts('./jscl.js');
(function(jscl){
'use strict';
(function(internals){ var values = internals.values;var l1=internals.make_lisp_string('JSCL/WORKER-REPL');
var l2=internals.intern('NIL','COMMON-LISP');
var l3=internals.intern('%DEFPACKAGE');
var l4=internals.intern('PACKAGE-USE-LIST','COMMON-LISP');
var l5=internals.intern('UNUSE-PACKAGE','COMMON-LISP');
var l6=internals.intern('SHADOW','COMMON-LISP');
var l7=internals.intern('FIND-SYMBOL-FOR-IMPORT');
var l8=internals.intern('MAPCAR','COMMON-LISP');
var l9=internals.intern('MAPCAN','COMMON-LISP');
var l10=internals.intern('SHADOWING-IMPORT','COMMON-LISP');
var l12=internals.intern('CL','KEYWORD');
l12.value=l12;
var l13=internals.intern('JSCL/FFI','KEYWORD');
l13.value=l13;
var l11=internals.QIList(l12,l13,l2);
var l14=internals.intern('USE-PACKAGE','COMMON-LISP');
var l15=internals.intern('IMPORT','COMMON-LISP');
var l16=internals.intern('INTERN','COMMON-LISP');
var l17=internals.intern('STRING','COMMON-LISP');
var l18=internals.intern('EXPORT','COMMON-LISP');
(function(v1){l5.fvalue(l4.fvalue(v1),v1);
l6.fvalue(l2,v1);
l10.fvalue(l9.fvalue((function JSCL_USER_NIL(v2){internals.checkArgs(arguments.length,1);
var v3=this;
return internals.mvcall(l8.fvalue,(function JSCL_USER_NIL(v4){internals.checkArgs(arguments.length,1);
var v5=this;
return internals.mvcall(l7.fvalue,v4,v2.$$jscl_car);
}),v2.$$jscl_cdr);
}),l2),v1);
l14.fvalue(l11,v1);
l15.fvalue(l9.fvalue((function JSCL_USER_NIL(v6){internals.checkArgs(arguments.length,1);
var v7=this;
return internals.mvcall(l8.fvalue,(function JSCL_USER_NIL(v8){internals.checkArgs(arguments.length,1);
var v9=this;
return internals.mvcall(l7.fvalue,v8,v6.$$jscl_car);
}),v6.$$jscl_cdr);
}),l2),v1);
(function(){return (function(v11,v12){(function(){while (v11!==l2.value){v12=v11.$$jscl_car;
l16.fvalue(v12,v1);
l2.value;
v11=v11.$$jscl_cdr;
}return l2.value;
})();
return l2.value;
})(l2,l2.value);
})();
l18.fvalue(l8.fvalue((function JSCL_USER_NIL(v13){internals.checkArgs(arguments.length,1);
var v14=this;
return internals.mvcall(l16.fvalue,l17.fvalue(v13),v1);
}),l2),v1);
l2.value;
return v1;
})(l3.fvalue(l1,l2));
var l19=internals.intern('*PACKAGE*','COMMON-LISP');
var l20=internals.intern('JSCL/WORKER-REPL','KEYWORD');
l20.value=l20;
var l21=internals.intern('FIND-PACKAGE-OR-FAIL');
l19.value=l21.fvalue(l20);
var l22=internals.intern('*WEB-WORKER-SESSION-ID*','JSCL/WORKER-REPL');
l22;
var l23=internals.intern('%WEB-WORKER-WRITE-STRING','JSCL/WORKER-REPL');
var l24=internals.make_lisp_string('jqconsole-output');
var l25=internals.make_lisp_string('command');
var l26=internals.make_lisp_string('stringclass');
var l27=internals.make_lisp_string('string');
var l28=internals.make_lisp_string('html');
var l29=internals.intern('*ROOT*');
l23.fvalue=(function(){var FUNC=(function JSCL_USER_WEBWORKERWRITESTRING(v15,v16,v17){internals.checkArgsAtLeast(arguments.length,1);
internals.checkArgsAtMost(arguments.length,3);
switch(arguments.length){case 1:v16=l24;
;
case 2:v17=l2.value;
;
default:break;
}var v18=this;
return (function(){return (function(v20){(function(){var v22=v20;
var v23=l25;
return (function(){var FUNC=(function JSCL_USER_NIL(v25){switch(arguments.length){case 0:v25=l2.value;
;
default:break;
}var v24=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v24=new internals.Cons(arguments[I],v24);
var v26=this;
return v22[internals.xstring(v23)]=v25;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1('output');
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
(function(){var v28=v20;
var v29=l26;
return (function(){var FUNC=(function JSCL_USER_NIL(v31){switch(arguments.length){case 0:v31=l2.value;
;
default:break;
}var v30=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v30=new internals.Cons(arguments[I],v30);
var v32=this;
return v28[internals.xstring(v29)]=v31;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.xstring(v16);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
(function(){var v34=v20;
var v35=l27;
return (function(){var FUNC=(function JSCL_USER_NIL(v37){switch(arguments.length){case 0:v37=l2.value;
;
default:break;
}var v36=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v36=new internals.Cons(arguments[I],v36);
var v38=this;
return v34[internals.xstring(v35)]=v37;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.xstring(v15);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
if (v17!==l2.value) (function(){var v40=v20;
var v41=l28;
return (function(){var FUNC=(function JSCL_USER_NIL(v43){switch(arguments.length){case 0:v43=l2.value;
;
default:break;
}var v42=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v42=new internals.Cons(arguments[I],v42);
var v44=this;
return v40[internals.xstring(v41)]=v43;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1(true);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
 else l2.value;
return internals.symbolValue(l29)['postMessage'](v20);
})({});
})();
});
FUNC.fname=internals.make_lisp_string('%WEB-WORKER-WRITE-STRING');
return FUNC;
})();
l23;
var l30=internals.intern('WEB-WORKER-REPL','JSCL/WORKER-REPL');
var l31=internals.intern('GET-REPL-PROMPT');
var l32=internals.make_lisp_string('jqconsole-prompt');
var l33=internals.intern('T','COMMON-LISP');
var l34=internals.intern('CLSTRING');
var l35=internals.intern('*ERROR-OUTPUT*','COMMON-LISP');
var l36=internals.intern('FORMAT-ERROR');
var l37=internals.intern('COMPLAINT','KEYWORD');
l37.value=l37;
var l38=internals.make_lisp_string('Required argument missing');
var l39=internals.intern('CONTROL-STRING','KEYWORD');
l39.value=l39;
var l40=internals.make_lisp_string('ERROR[!]: ~a~%~A~%');
var l41=internals.intern('OFFSET','KEYWORD');
l41.value=l41;
var l42=internals.intern('ERROR','COMMON-LISP');
var l43=internals.make_lisp_string('ERROR[!]: ');
var l44=internals.intern('WRITE-STRING','COMMON-LISP');
var l45=internals.intern('PRINC','COMMON-LISP');
var l46=internals.intern('TERPRI','COMMON-LISP');
var l47=internals.make_lisp_string('');
var l48=internals.intern('CALL-FORMATTER');
var l49=internals.intern('*HANDLER-BINDINGS*');
var l50=internals.intern('SERIOUS-CONDITION','COMMON-LISP');
var l51=internals.make_lisp_string('~A: ~A~%');
var l52=internals.make_lisp_string(': ');
var l53=internals.intern('CLASS-OF','COMMON-LISP');
var l54=internals.intern('CLASS-NAME','COMMON-LISP');
var l55=internals.intern('*TRACE-OUTPUT*','COMMON-LISP');
var l56=internals.intern('FROM','KEYWORD');
l56.value=l56;
var l57=internals.intern('SIGNAL','COMMON-LISP');
var l58=internals.intern('FORMAT-BACKTRACE');
var l59=internals.intern('%%ERROR');
var l60=internals.intern('LIST','COMMON-LISP');
var l61=internals.intern('READ','COMMON-LISP');
var l62=internals.intern('EVAL-INTERACTIVE');
var l63=internals.intern('FRESH-LINE','COMMON-LISP');
var l64=internals.intern('PRIN1','COMMON-LISP');
l30.fvalue=(function(){var FUNC=(function JSCL_USER_WEBWORKERREPL(){internals.checkArgsAtMost(arguments.length,0);
var v45=this;
return (function(){return (function(){return (function(){var v48=1;
var v49=[];
TBLOOP:while (true){try{switch(v48){case 1:{l23.fvalue(l31.fvalue(),l32);
(function(){try{return (function(){try{var v59=[];
return (function(v60){return internals.bindSpecialBindings([l49],[v60],(function(){(function(){var v62=new internals.Cons(l50,(function JSCL_USER_NIL(v63){internals.checkArgs(arguments.length,1);
var v64=this;
l48.fvalue(internals.symbolValue(l35),(function JSCL_USER_NIL(v66,v67,v68){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v67=l42.fvalue(l36,l37.value,l38,l39.value,l51,l41.value,1);
;
case 2:v68=l42.fvalue(l36,l37.value,l38,l39.value,l51,l41.value,5);
;
default:break;
}var v65=l2.value;
var I;
for (I=arguments.length-1;I>=3;I--)v65=new internals.Cons(arguments[I],v65);
var v69=this;
(function(){l45.fvalue(v67,v66);
l44.fvalue(l52,v66);
l45.fvalue(v68,v66);
return l46.fvalue(v66);
})();
return internals.values1(v65);
}),l54.fvalue(l53.fvalue(v63)),v63);
l58.fvalue(internals.symbolValue(l55),l56.value,internals.symbolFunction(l57));
return (function(){throw new internals.BlockNLX(v59,l2.value,null,'BAIL-OUT');
})();
}));
var v71=new internals.Cons(v62,internals.symbolValue(l49));
return l49.value=v71;
})();
return (function(){try{return (function(){return (function(v75,v76){(function(){while (v75!==l2.value){v76=v75.$$jscl_car;
l63.fvalue();
l64.fvalue(v76);
l46.fvalue();
l2.value;
v75=v75.$$jscl_cdr;
}return l2.value;
})();
return l2.value;
})((function(){var FUNC=internals.symbolFunction(l60);
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.mvcall(l62.fvalue,l61.fvalue());
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})(),l2.value);
})();
}catch (v72){return (internals.isNLX(v72)?l33.value:l2.value)!==l2.value?(function(){throw v72;
})():l59.fvalue((function(v73){return (v73===undefined?l33.value:l2.value)!==l2.value?l34.fvalue(v72):l34.fvalue(v73);
})(v72['message']));
}})();
}));
})(internals.symbolValue(l49));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v59) return CF.value;
 else throw CF;
}})();
}catch (v50){return (function(v52){return l48.fvalue(internals.symbolValue(l35),(function JSCL_USER_NIL(v54,v55,v56){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v55=l42.fvalue(l36,l37.value,l38,l39.value,l40,l41.value,11);
;
case 2:v56=l42.fvalue(l36,l37.value,l38,l39.value,l40,l41.value,15);
;
default:break;
}var v53=l2.value;
var I;
for (I=arguments.length-1;I>=3;I--)v53=new internals.Cons(arguments[I],v53);
var v57=this;
(function(){l44.fvalue(l43,v54);
l45.fvalue(v55,v54);
l46.fvalue(v54);
l45.fvalue(v56,v54);
return l46.fvalue(v54);
})();
return internals.values1(v53);
}),v52,l34.fvalue(v50['stack']??l47));
})((function(v51){return (v51===undefined?l33.value:l2.value)!==l2.value?l34.fvalue(v50):l34.fvalue(v51);
})(v50['message']));
}})();
}(function(){throw new internals.TagNLX(v49,1);
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v49) v48=JUMP.label;
 else throw JUMP;
}}return l2.value;
})();
})();
})();
});
FUNC.fname=internals.make_lisp_string('WEB-WORKER-REPL');
return FUNC;
})();
l30;
var l65=internals.intern('SW-REQUEST-SYNC','JSCL/WORKER-REPL');
var l66=internals.make_lisp_string('command');
var l67=internals.make_lisp_string('sessionId');
var l68=internals.make_lisp_string('options');
var l69=internals.intern('EQL','COMMON-LISP');
var l70=internals.make_lisp_string('wait');
var l71=internals.make_lisp_string('Could not contact with the service worker.');
l65.fvalue=(function(){var FUNC=(function JSCL_USER_SWREQUESTSYNC(v77,v78){internals.checkArgsAtLeast(arguments.length,1);
internals.checkArgsAtMost(arguments.length,2);
switch(arguments.length){case 1:v78={};
;
default:break;
}var v79=this;
return (function(){return (function(){try{var v81=[];
return (function(){var v82=1;
var v83=[];
TBLOOP:while (true){try{switch(v82){case 1:(function(v84,v85){(function(){var v87=v85;
var v88=l66;
return (function(){var FUNC=(function JSCL_USER_NIL(v90){switch(arguments.length){case 0:v90=l2.value;
;
default:break;
}var v89=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v89=new internals.Cons(arguments[I],v89);
var v91=this;
return v87[internals.xstring(v88)]=v90;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.xstring(v77);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
(function(){var v93=v85;
var v94=l67;
return (function(){var FUNC=(function JSCL_USER_NIL(v96){switch(arguments.length){case 0:v96=l2.value;
;
default:break;
}var v95=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v95=new internals.Cons(arguments[I],v95);
var v97=this;
return v93[internals.xstring(v94)]=v96;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.symbolValue(l22);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
(function(){var v99=v85;
var v100=l68;
return (function(){var FUNC=(function JSCL_USER_NIL(v102){switch(arguments.length){case 0:v102=l2.value;
;
default:break;
}var v101=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v101=new internals.Cons(arguments[I],v101);
var v103=this;
return v99[internals.xstring(v100)]=v102;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1(v78);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
v84['open']('POST','__jscl',false);
v84['setRequestHeader']('ContentType','application/json');
v84['send'](internals.symbolValue(l29)['JSON']['stringify'](v85));
return l69.fvalue(v84['status'],200)!==l2.value?(function(){var v105=v84['responseText'];
var v106=internals.symbolValue(l29)['JSON']['parse'](v105);
return (('timeout' in v106?l33.value:l2.value)!==l2.value?v106['timeout']:l2.value)!==l2.value?(v77=l70):(function(){var _R=internals.withMV((function(){return v106['value'];
}));
throw new internals.BlockNLX(v81,_R.result,_R.mv,'NIL');
})();
})():l42.fvalue(l71);
})(internals.newInstance(internals.symbolValue(l29)['XMLHttpRequest']),{});
(function(){throw new internals.TagNLX(v83,1);
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v83) v82=JUMP.label;
 else throw JUMP;
}}return l2.value;
})();
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v81) {internals._mv=CF.mv;
return CF.value;
} else throw CF;
}})();
})();
});
FUNC.fname=internals.make_lisp_string('SW-REQUEST-SYNC');
return FUNC;
})();
l65;
var l72=internals.intern('SLEEP','COMMON-LISP');
var l73=internals.make_lisp_string('seconds');
var l74=internals.make_lisp_string('sleep');
l72.fvalue=(function(){var FUNC=(function JSCL_USER_SLEEP(v107){internals.checkArgs(arguments.length,1);
var v108=this;
return (function(){return (function(v110){(function(){var v112=v110;
var v113=l73;
return (function(){var FUNC=(function JSCL_USER_NIL(v115){switch(arguments.length){case 0:v115=l2.value;
;
default:break;
}var v114=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v114=new internals.Cons(arguments[I],v114);
var v116=this;
return v112[internals.xstring(v113)]=v115;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1(v107);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
l65.fvalue(l74,v110);
return internals.values1(l2.value);
})({});
})();
});
FUNC.fname=internals.make_lisp_string('SLEEP');
return FUNC;
})();
l72;
var l75=internals.intern('*STDIN-BUFFER*','JSCL/WORKER-REPL');
if ((l75.value!==internals.UNBOUND?l33.value:l2.value)!==l2.value) l2.value;
 else l75.value=l47;
l75;
var l76=internals.intern('READ-STDIN','JSCL/WORKER-REPL');
var l77=internals.make_lisp_string('readStdin');
var l78=internals.intern('CONCATENATE','COMMON-LISP');
l76.fvalue=(function(){var FUNC=(function JSCL_USER_READSTDIN(){internals.checkArgsAtMost(arguments.length,0);
var v117=this;
return (function(){return (function(v119){(function(){return (function(){var FUNC=(function JSCL_USER_NIL(v122){switch(arguments.length){case 0:v122=l2.value;
;
default:break;
}var v121=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v121=new internals.Cons(arguments[I],v121);
var v123=this;
return l75.value=v122;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.mvcall(l78.fvalue,l17,internals.symbolValue(l75),v119);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
return internals.symbolValue(l75);
})(l34.fvalue(l65.fvalue(l77)));
})();
});
FUNC.fname=internals.make_lisp_string('READ-STDIN');
return FUNC;
})();
l76;
var l79=internals.intern('CLEAR-BUFFER','JSCL/WORKER-REPL');
l79.fvalue=(function(){var FUNC=(function JSCL_USER_CLEARBUFFER(){internals.checkArgsAtMost(arguments.length,0);
var v124=this;
return (function(){return (function(){return (function(){var FUNC=(function JSCL_USER_NIL(v128){switch(arguments.length){case 0:v128=l2.value;
;
default:break;
}var v127=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v127=new internals.Cons(arguments[I],v127);
var v129=this;
return l75.value=v128;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1(l47);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
})();
});
FUNC.fname=internals.make_lisp_string('CLEAR-BUFFER');
return FUNC;
})();
l79;
var l80=internals.intern('%PEEK-CHAR-STDIN','JSCL/WORKER-REPL');
var l81=internals.intern('LENGTH','COMMON-LISP');
var l82=internals.intern('NUMBER','COMMON-LISP');
var l83=internals.intern('CHAR','COMMON-LISP');
l80.fvalue=(function(){var FUNC=(function JSCL_USER_PEEKCHARSTDIN(){var v130=l2.value;
var I;
for (I=arguments.length-1;I>=0;I--)v130=new internals.Cons(arguments[I],v130);
var v131=this;
return (function(){return (function(){var x1=l81.fvalue(internals.symbolValue(l75));
if (typeof x1!='number') internals.typeError(x1,l82);
return 0<x1?l33.value:l2.value;
})()!==l2.value?internals.mvcall(l83.fvalue,internals.symbolValue(l75),0):(l76.fvalue(),(function(){var F=internals.symbolFunction(l80);
var ARGS=[];
var TAIL=v130;
while (TAIL!=l2.value){ARGS.push(TAIL.$$jscl_car);
TAIL=TAIL.$$jscl_cdr;
}return internals.mvcall(typeof F==='function'?F:F.fvalue,...ARGS);
})());
})();
});
FUNC.fname=internals.make_lisp_string('%PEEK-CHAR-STDIN');
return FUNC;
})();
l80;
var l84=internals.intern('%READ-CHAR-STDIN','JSCL/WORKER-REPL');
var l85=internals.intern('SUBSEQ','COMMON-LISP');
l84.fvalue=(function(){var FUNC=(function JSCL_USER_READCHARSTDIN(){var v133=l2.value;
var I;
for (I=arguments.length-1;I>=0;I--)v133=new internals.Cons(arguments[I],v133);
var v134=this;
return (function(){return (function(v136){(function(){return (function(){var FUNC=(function JSCL_USER_NIL(v139){switch(arguments.length){case 0:v139=l2.value;
;
default:break;
}var v138=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v138=new internals.Cons(arguments[I],v138);
var v140=this;
return l75.value=v139;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.mvcall(l85.fvalue,internals.symbolValue(l75),1);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
return internals.values1(v136);
})((function(){var F=internals.symbolFunction(l80);
var ARGS=[];
var TAIL=v133;
while (TAIL!=l2.value){ARGS.push(TAIL.$$jscl_car);
TAIL=TAIL.$$jscl_cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})());
})();
});
FUNC.fname=internals.make_lisp_string('%READ-CHAR-STDIN');
return FUNC;
})();
l84;
var l86=internals.intern('WRITE-WELCOME-MESSAGE','JSCL/WORKER-REPL');
var l87=internals.intern('WELCOME-MESSAGE-ITEMS');
var l88=internals.intern('FIRST','COMMON-LISP');
var l89=internals.intern('STR','KEYWORD');
l89.value=l89;
var l90=internals.intern('SECOND','COMMON-LISP');
var l91=internals.intern('BOLD','KEYWORD');
l91.value=l91;
var l92=internals.make_lisp_string('<strong>~a</strong>');
var l93=internals.make_lisp_string('<strong>');
var l94=internals.make_lisp_string('</strong>');
var l95=internals.make_lisp_string('jqconsole-output');
var l96=internals.intern('LINK','KEYWORD');
l96.value=l96;
var l97=internals.make_lisp_string('<a href="~a" target="_blank">~a</a>');
var l98=internals.make_lisp_string('<a href="');
var l99=internals.make_lisp_string('" target="_blank">');
var l100=internals.make_lisp_string('</a>');
var l101=internals.intern('THIRD','COMMON-LISP');
var l102=internals.make_lisp_string('jqconsole-output');
var l103=internals.intern('NEWLINE','KEYWORD');
l103.value=l103;
var l104=internals.make_lisp_string("ECASE expression failed for the object `~S'.");
l86.fvalue=(function(){var FUNC=(function JSCL_USER_WRITEWELCOMEMESSAGE(){internals.checkArgsAtMost(arguments.length,0);
var v141=this;
return (function(){return (function(){return (function(v144,v145){(function(){while (v144!==l2.value){v145=v144.$$jscl_car;
(function(v146){return (function(v147){return l69.fvalue(v147,l89)!==l2.value?(l2.value,l23.fvalue(l90.fvalue(v145))):l69.fvalue(v147,l91)!==l2.value?(l2.value,l23.fvalue(l48.fvalue(l2.value,(function JSCL_USER_NIL(v149,v150){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v150=l42.fvalue(l36,l37.value,l38,l39.value,l92,l41.value,9);
;
default:break;
}var v148=l2.value;
var I;
for (I=arguments.length-1;I>=2;I--)v148=new internals.Cons(arguments[I],v148);
var v151=this;
(function(){l44.fvalue(l93,v149);
l45.fvalue(v150,v149);
return l44.fvalue(l94,v149);
})();
return internals.values1(v148);
}),l90.fvalue(v145)),l95,l33.value)):l69.fvalue(v147,l96)!==l2.value?(l2.value,l23.fvalue(l48.fvalue(l2.value,(function JSCL_USER_NIL(v154,v155,v156){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v155=l42.fvalue(l36,l37.value,l38,l39.value,l97,l41.value,10);
;
case 2:v156=l42.fvalue(l36,l37.value,l38,l39.value,l97,l41.value,30);
;
default:break;
}var v153=l2.value;
var I;
for (I=arguments.length-1;I>=3;I--)v153=new internals.Cons(arguments[I],v153);
var v157=this;
(function(){l44.fvalue(l98,v154);
l45.fvalue(v155,v154);
l44.fvalue(l99,v154);
l45.fvalue(v156,v154);
return l44.fvalue(l100,v154);
})();
return internals.values1(v153);
}),l101.fvalue(v145),l90.fvalue(v145)),l102,l33.value)):l69.fvalue(v147,l103)!==l2.value?(l2.value,l23.fvalue(l17.fvalue('\n'))):(l2.value,l42.fvalue(l104,v146));
})(v146);
})(l88.fvalue(v145));
l2.value;
v144=v144.$$jscl_cdr;
}return l2.value;
})();
return internals.values1(l2.value);
})(l87.fvalue(),l2.value);
})();
})();
});
FUNC.fname=internals.make_lisp_string('WRITE-WELCOME-MESSAGE');
FUNC.docstring=internals.make_lisp_string('Render the welcome message as HTML via the web worker output.');
return FUNC;
})();
l86;
var l105=internals.intern('INITIALIZE-WEB-WORKER','JSCL/WORKER-REPL');
var l106=internals.intern('*STANDARD-OUTPUT*','COMMON-LISP');
var l107=internals.intern('WRITE-FN','KEYWORD');
l107.value=l107;
var l108=internals.intern('MAKE-STREAM');
var l109=internals.make_lisp_string('jqconsole-error');
var l110=internals.intern('*STANDARD-INPUT*','COMMON-LISP');
var l111=internals.intern('READ-CHAR-FN','KEYWORD');
l111.value=l111;
var l112=internals.intern('PEEK-CHAR-FN','KEYWORD');
l112.value=l112;
var l113=internals.make_lisp_string('CL-USER');
var l114=internals.intern('FIND-PACKAGE','COMMON-LISP');
var l115=internals.make_lisp_string('onmessage');
var l116=internals.make_lisp_string('init');
var l117=internals.intern('STRING=','COMMON-LISP');
l105.fvalue=(function(){var FUNC=(function JSCL_USER_INITIALIZEWEBWORKER(){internals.checkArgsAtMost(arguments.length,0);
var v159=this;
return (function(){l106.value=l108.fvalue(l107.value,internals.symbolFunction(l23));
l35.value=l108.fvalue(l107.value,(function JSCL_USER_NIL(v161){internals.checkArgs(arguments.length,1);
var v162=this;
return internals.mvcall(l23.fvalue,v161,l109);
}));
l55.value=internals.symbolValue(l106);
l110.value=l108.fvalue(l111.value,internals.symbolFunction(l84),l112.value,internals.symbolFunction(l80));
l19.value=l114.fvalue(l113);
l86.fvalue();
return (function(){var v164=internals.symbolValue(l29);
var v165=l115;
return (function(){var FUNC=(function JSCL_USER_NIL(v167){switch(arguments.length){case 0:v167=l2.value;
;
default:break;
}var v166=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v166=new internals.Cons(arguments[I],v166);
var v168=this;
return v164[internals.xstring(v165)]=v167;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return (function JSCL_USER_NIL(v169){internals.checkArgs(arguments.length,1);
var v170=this;
return (function(){var v172=v169['data'];
var v173=l34.fvalue(v172['command']);
var v174=v172['sessionId'];
return l117.fvalue(v173,l116)!==l2.value?((function(){return (function(){var FUNC=(function JSCL_USER_NIL(v177){switch(arguments.length){case 0:v177=l2.value;
;
default:break;
}var v176=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v176=new internals.Cons(arguments[I],v176);
var v178=this;
return l22.value=v177;
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1(v174);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})(),internals.mvcall(l30.fvalue)):internals.values1(l2.value);
})();
});
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})();
})();
});
FUNC.fname=internals.make_lisp_string('INITIALIZE-WEB-WORKER');
return FUNC;
})();
l105;
l105.fvalue();
})(jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'):
typeof window !== 'undefined'? window.jscl: self.jscl )