#!/usr/bin/env node
if (typeof importScripts !== 'undefined') importScripts('./jscl.js');
(function(jscl){
'use strict';
(function(internals){ var values = internals.values;var l1=internals.make_lisp_string('JSCL/NODE-REPL');
var l2=internals.intern('NIL','COMMON-LISP');
var l3=internals.intern('%DEFPACKAGE');
var l4=internals.intern('PACKAGE-USE-LIST','COMMON-LISP');
var l5=internals.intern('UNUSE-PACKAGE','COMMON-LISP');
var l6=internals.intern('SHADOW','COMMON-LISP');
var l7=internals.intern('FIND-SYMBOL-FOR-IMPORT');
var l8=internals.intern('MAPCAR','COMMON-LISP');
var l9=internals.intern('MAPCAN','COMMON-LISP');
var l10=internals.intern('SHADOWING-IMPORT','COMMON-LISP');
var l12=internals.intern('CL','KEYWORD');
l12.value=l12;
var l11=internals.QIList(l12,l2);
var l13=internals.intern('USE-PACKAGE','COMMON-LISP');
var l14=internals.intern('IMPORT','COMMON-LISP');
var l15=internals.intern('INTERN','COMMON-LISP');
var l16=internals.intern('STRING','COMMON-LISP');
var l17=internals.intern('EXPORT','COMMON-LISP');
(function(v1){l5.fvalue(l4.fvalue(v1),v1);
l6.fvalue(l2,v1);
l10.fvalue(l9.fvalue((function JSCL_USER_NIL(v2){internals.checkArgs(arguments.length,1);
var v3=this;
return internals.mvcall(l8.fvalue,(function JSCL_USER_NIL(v4){internals.checkArgs(arguments.length,1);
var v5=this;
return internals.mvcall(l7.fvalue,v4,v2.$$jscl_car);
}),v2.$$jscl_cdr);
}),l2),v1);
l13.fvalue(l11,v1);
l14.fvalue(l9.fvalue((function JSCL_USER_NIL(v6){internals.checkArgs(arguments.length,1);
var v7=this;
return internals.mvcall(l8.fvalue,(function JSCL_USER_NIL(v8){internals.checkArgs(arguments.length,1);
var v9=this;
return internals.mvcall(l7.fvalue,v8,v6.$$jscl_car);
}),v6.$$jscl_cdr);
}),l2),v1);
(function(){return (function(v11,v12){(function(){while (v11!==l2.value){v12=v11.$$jscl_car;
l15.fvalue(v12,v1);
l2.value;
v11=v11.$$jscl_cdr;
}return l2.value;
})();
return l2.value;
})(l2,l2.value);
})();
l17.fvalue(l8.fvalue((function JSCL_USER_NIL(v13){internals.checkArgs(arguments.length,1);
var v14=this;
return internals.mvcall(l15.fvalue,l16.fvalue(v13),v1);
}),l2),v1);
l2.value;
return v1;
})(l3.fvalue(l1,l2));
var l18=internals.intern('*PACKAGE*','COMMON-LISP');
var l19=internals.intern('JSCL/NODE-REPL','KEYWORD');
l19.value=l19;
var l20=internals.intern('FIND-PACKAGE-OR-FAIL');
l18.value=l20.fvalue(l19);
var l21=internals.intern('REQUIRE','COMMON-LISP');
l21.fvalue=(function(){var FUNC=(function JSCL_USER_REQUIRE(v15){internals.checkArgs(arguments.length,1);
var v16=this;
return (function(){return (function(){var F=require;
return internals.mvcall(typeof F==='function'?F:F.fvalue,internals.xstring(v15));
})();
})();
});
FUNC.fname=internals.make_lisp_string('REQUIRE');
FUNC.docstring=internals.make_lisp_string('Load a Node.js module by NAME.');
return FUNC;
})();
l21;
var l22=internals.intern('*REPL*','JSCL/NODE-REPL');
l22;
var l23=internals.intern('START-REPL','JSCL/NODE-REPL');
var l24=internals.intern('WELCOME-MESSAGE');
var l25=internals.intern('CLSTRING');
var l26=internals.intern('NSUBSTITUTE','COMMON-LISP');
var l27=internals.intern('%SEXPR-INCOMPLETE');
var l28=internals.intern('*ROOT*');
var l29=internals.intern('T','COMMON-LISP');
var l30=internals.intern('*ERROR-OUTPUT*','COMMON-LISP');
var l31=internals.intern('FORMAT-ERROR');
var l32=internals.intern('COMPLAINT','KEYWORD');
l32.value=l32;
var l33=internals.make_lisp_string('Required argument missing');
var l34=internals.intern('CONTROL-STRING','KEYWORD');
l34.value=l34;
var l35=internals.make_lisp_string('ERROR[!]: ~a~%~A~%');
var l36=internals.intern('OFFSET','KEYWORD');
l36.value=l36;
var l37=internals.intern('ERROR','COMMON-LISP');
var l38=internals.make_lisp_string('ERROR[!]: ');
var l39=internals.intern('WRITE-STRING','COMMON-LISP');
var l40=internals.intern('PRINC','COMMON-LISP');
var l41=internals.intern('TERPRI','COMMON-LISP');
var l42=internals.make_lisp_string('');
var l43=internals.intern('CALL-FORMATTER');
var l44=internals.intern('*HANDLER-BINDINGS*');
var l45=internals.intern('SERIOUS-CONDITION','COMMON-LISP');
var l46=internals.make_lisp_string('~A: ~A~%');
var l47=internals.make_lisp_string(': ');
var l48=internals.intern('CLASS-OF','COMMON-LISP');
var l49=internals.intern('CLASS-NAME','COMMON-LISP');
var l50=internals.intern('*TRACE-OUTPUT*','COMMON-LISP');
var l51=internals.intern('FROM','KEYWORD');
l51.value=l51;
var l52=internals.intern('SIGNAL','COMMON-LISP');
var l53=internals.intern('FORMAT-BACKTRACE');
var l54=internals.intern('%%ERROR');
var l55=internals.intern('LIST','COMMON-LISP');
var l56=internals.intern('EVAL-INTERACTIVE-INPUT');
var l57=internals.intern('FRESH-LINE','COMMON-LISP');
var l58=internals.intern('PRIN1','COMMON-LISP');
var l59=internals.intern('GET-REPL-PROMPT');
l23.fvalue=(function(){var FUNC=(function JSCL_USER_STARTREPL(){internals.checkArgsAtMost(arguments.length,0);
var v18=this;
return (function(){l24.fvalue();
return (function(){var v20=(function JSCL_USER_NIL(v21,v22,v23,v24){internals.checkArgs(arguments.length,4);
var v25=this;
return (function(){return (function(v27){v27=l26.fvalue(internals.char_from_codepoint(10),internals.char_from_codepoint(13),v27);
return l27.fvalue(v27)!==l2.value?(function(){var F=v24;
return internals.mvcall(typeof F==='function'?F:F.fvalue,internals.newInstance(internals.symbolValue(l28)['repl']['Recoverable']));
})():((function(){try{return (function(){try{var v37=[];
return (function(v38){return internals.bindSpecialBindings([l44],[v38],(function(){(function(){var v40=new internals.Cons(l45,(function JSCL_USER_NIL(v41){internals.checkArgs(arguments.length,1);
var v42=this;
l43.fvalue(internals.symbolValue(l30),(function JSCL_USER_NIL(v44,v45,v46){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v45=l37.fvalue(l31,l32.value,l33,l34.value,l46,l36.value,1);
;
case 2:v46=l37.fvalue(l31,l32.value,l33,l34.value,l46,l36.value,5);
;
default:break;
}var v43=l2.value;
var I;
for (I=arguments.length-1;I>=3;I--)v43=new internals.Cons(arguments[I],v43);
var v47=this;
(function(){l40.fvalue(v45,v44);
l39.fvalue(l47,v44);
l40.fvalue(v46,v44);
return l41.fvalue(v44);
})();
return internals.values1(v43);
}),l49.fvalue(l48.fvalue(v41)),v41);
l53.fvalue(internals.symbolValue(l50),l51.value,internals.symbolFunction(l52));
return (function(){throw new internals.BlockNLX(v37,l2.value,null,'BAIL-OUT');
})();
}));
var v49=new internals.Cons(v40,internals.symbolValue(l44));
return l44.value=v49;
})();
return (function(){try{return (function(){return (function(v53,v54){(function(){while (v53!==l2.value){v54=v53.$$jscl_car;
l57.fvalue();
l58.fvalue(v54);
l41.fvalue();
l2.value;
v53=v53.$$jscl_cdr;
}return l2.value;
})();
return l2.value;
})((function(){var FUNC=internals.symbolFunction(l55);
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.mvcall(l56.fvalue,v27);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})(),l2.value);
})();
}catch (v50){return (internals.isNLX(v50)?l29.value:l2.value)!==l2.value?(function(){throw v50;
})():l54.fvalue((function(v51){return (v51===undefined?l29.value:l2.value)!==l2.value?l25.fvalue(v50):l25.fvalue(v51);
})(v50['message']));
}})();
}));
})(internals.symbolValue(l44));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v37) return CF.value;
 else throw CF;
}})();
}catch (v28){return (function(v30){return l43.fvalue(internals.symbolValue(l30),(function JSCL_USER_NIL(v32,v33,v34){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v33=l37.fvalue(l31,l32.value,l33,l34.value,l35,l36.value,11);
;
case 2:v34=l37.fvalue(l31,l32.value,l33,l34.value,l35,l36.value,15);
;
default:break;
}var v31=l2.value;
var I;
for (I=arguments.length-1;I>=3;I--)v31=new internals.Cons(arguments[I],v31);
var v35=this;
(function(){l39.fvalue(l38,v32);
l40.fvalue(v33,v32);
l41.fvalue(v32);
l40.fvalue(v34,v32);
return l41.fvalue(v32);
})();
return internals.values1(v31);
}),v30,l25.fvalue(v28['stack']??l42));
})((function(v29){return (v29===undefined?l29.value:l2.value)!==l2.value?l25.fvalue(v28):l25.fvalue(v29);
})(v28['message']));
}})(),internals.symbolValue(l22)['setPrompt'](internals.xstring(l59.fvalue())),(function(){var F=v24;
return internals.mvcall(typeof F==='function'?F:F.fvalue,null);
})());
})(l25.fvalue(v21));
})();
});
return l22.value=internals.symbolValue(l28)['repl']['start']({input: internals.symbolValue(l28)['process']['stdin'],output: internals.symbolValue(l28)['process']['stdout'],eval: v20,writer: (function JSCL_USER_NIL(){var v57=l2.value;
var I;
for (I=arguments.length-1;I>=0;I--)v57=new internals.Cons(arguments[I],v57);
var v58=this;
return internals.values1('');
}),prompt: internals.xstring(l59.fvalue())});
})();
})();
});
FUNC.fname=internals.make_lisp_string('START-REPL');
return FUNC;
})();
l23;
var l60=internals.intern('NODE-INIT','JSCL/NODE-REPL');
var l61=internals.intern('*STANDARD-OUTPUT*','COMMON-LISP');
var l62=internals.intern('WRITE-FN','KEYWORD');
l62.value=l62;
var l63=internals.intern('MAKE-STREAM');
var l64=internals.make_lisp_string('CL-USER');
var l65=internals.intern('FIND-PACKAGE','COMMON-LISP');
var l66=internals.intern('SUBSEQ','COMMON-LISP');
var l67=internals.intern('VECTOR-TO-LIST');
var l68=internals.intern('NULL','COMMON-LISP');
var l69=internals.intern('LOAD','COMMON-LISP');
l60.fvalue=(function(){var FUNC=(function JSCL_USER_NODEINIT(){internals.checkArgsAtMost(arguments.length,0);
var v59=this;
return (function(){l61.value=l63.fvalue(l62.value,(function JSCL_USER_NIL(v61){internals.checkArgs(arguments.length,1);
var v62=this;
return internals.symbolValue(l28)['process']['stdout']['write'](internals.xstring(v61));
}));
l30.value=internals.symbolValue(l61);
l50.value=internals.symbolValue(l61);
l18.value=l65.fvalue(l64);
return (function(v63){return l68.fvalue(v63)!==l2.value?internals.mvcall(l23.fvalue):(function(){return (function(v65,v66){(function(){while (v65!==l2.value){v66=v65.$$jscl_car;
l69.fvalue(v66);
l2.value;
v65=v65.$$jscl_cdr;
}return l2.value;
})();
return internals.values1(l2.value);
})(v63,l2.value);
})();
})(l8.fvalue(internals.symbolFunction(l25),l67.fvalue(l66.fvalue(internals.symbolValue(l28)['process']['argv'],2))));
})();
});
FUNC.fname=internals.make_lisp_string('NODE-INIT');
return FUNC;
})();
l60;
l60.fvalue();
})(jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'):
typeof window !== 'undefined'? window.jscl: self.jscl )