if (typeof importScripts !== 'undefined') importScripts('./jscl.js');
(function(jscl){
'use strict';
(function(internals){ var values = internals.values;var l1=internals.make_lisp_string('JSCL/DENO-REPL');
var l2=internals.intern('NIL','COMMON-LISP');
var l3=internals.intern('%DEFPACKAGE');
var l4=internals.intern('PACKAGE-USE-LIST','COMMON-LISP');
var l5=internals.intern('UNUSE-PACKAGE','COMMON-LISP');
var l6=internals.intern('SHADOW','COMMON-LISP');
var l7=internals.intern('FIND-SYMBOL-FOR-IMPORT');
var l8=internals.intern('MAPCAR','COMMON-LISP');
var l9=internals.intern('MAPCAN','COMMON-LISP');
var l10=internals.intern('SHADOWING-IMPORT','COMMON-LISP');
var l12=internals.intern('CL','KEYWORD');
l12.value=l12;
var l13=internals.intern('JSCL/FFI','KEYWORD');
l13.value=l13;
var l11=internals.QIList(l12,l13,l2);
var l14=internals.intern('USE-PACKAGE','COMMON-LISP');
var l15=internals.intern('IMPORT','COMMON-LISP');
var l16=internals.intern('INTERN','COMMON-LISP');
var l17=internals.intern('STRING','COMMON-LISP');
var l18=internals.intern('EXPORT','COMMON-LISP');
(function(v1){l5.fvalue(l4.fvalue(v1),v1);
l6.fvalue(l2,v1);
l10.fvalue(l9.fvalue((function JSCL_USER_NIL(v2){internals.checkArgs(arguments.length,1);
var v3=this;
return internals.mvcall(l8.fvalue,(function JSCL_USER_NIL(v4){internals.checkArgs(arguments.length,1);
var v5=this;
return internals.mvcall(l7.fvalue,v4,v2.$$jscl_car);
}),v2.$$jscl_cdr);
}),l2),v1);
l14.fvalue(l11,v1);
l15.fvalue(l9.fvalue((function JSCL_USER_NIL(v6){internals.checkArgs(arguments.length,1);
var v7=this;
return internals.mvcall(l8.fvalue,(function JSCL_USER_NIL(v8){internals.checkArgs(arguments.length,1);
var v9=this;
return internals.mvcall(l7.fvalue,v8,v6.$$jscl_car);
}),v6.$$jscl_cdr);
}),l2),v1);
(function(){return (function(v11,v12){(function(){while (v11!==l2.value){v12=v11.$$jscl_car;
l16.fvalue(v12,v1);
l2.value;
v11=v11.$$jscl_cdr;
}return l2.value;
})();
return l2.value;
})(l2,l2.value);
})();
l18.fvalue(l8.fvalue((function JSCL_USER_NIL(v13){internals.checkArgs(arguments.length,1);
var v14=this;
return internals.mvcall(l16.fvalue,l17.fvalue(v13),v1);
}),l2),v1);
l2.value;
return v1;
})(l3.fvalue(l1,l2));
var l19=internals.intern('*PACKAGE*','COMMON-LISP');
var l20=internals.intern('JSCL/DENO-REPL','KEYWORD');
l20.value=l20;
var l21=internals.intern('FIND-PACKAGE-OR-FAIL');
l19.value=l21.fvalue(l20);
var l22=internals.intern('*RL*','JSCL/DENO-REPL');
l22;
var l23=internals.intern('START-REPL','JSCL/DENO-REPL');
var l24=internals.intern('WELCOME-MESSAGE');
var l25=internals.intern('*ROOT*');
var l26=internals.intern('MAKE-STRING-OUTPUT-STREAM','COMMON-LISP');
var l27=internals.intern('GET-REPL-PROMPT');
var l28=internals.intern('LENGTH','COMMON-LISP');
var l29=internals.intern('1-','COMMON-LISP');
var l30=internals.intern('INITIAL-ELEMENT','KEYWORD');
l30.value=l30;
var l31=internals.intern('MAKE-STRING','COMMON-LISP');
var l32=internals.make_lisp_string(' ');
var l33=internals.intern('CONCATENATE','COMMON-LISP');
var l34=internals.intern('CLSTRING');
var l35=internals.intern('WRITE-LINE','COMMON-LISP');
var l36=internals.intern('STREAM-DATA');
var l37=internals.intern('%SEXPR-INCOMPLETE');
var l38=internals.intern('T','COMMON-LISP');
var l39=internals.intern('*ERROR-OUTPUT*','COMMON-LISP');
var l40=internals.intern('FORMAT-ERROR');
var l41=internals.intern('COMPLAINT','KEYWORD');
l41.value=l41;
var l42=internals.make_lisp_string('Required argument missing');
var l43=internals.intern('CONTROL-STRING','KEYWORD');
l43.value=l43;
var l44=internals.make_lisp_string('ERROR[!]: ~a~%~A~%');
var l45=internals.intern('OFFSET','KEYWORD');
l45.value=l45;
var l46=internals.intern('ERROR','COMMON-LISP');
var l47=internals.make_lisp_string('ERROR[!]: ');
var l48=internals.intern('WRITE-STRING','COMMON-LISP');
var l49=internals.intern('PRINC','COMMON-LISP');
var l50=internals.intern('TERPRI','COMMON-LISP');
var l51=internals.make_lisp_string('');
var l52=internals.intern('CALL-FORMATTER');
var l53=internals.intern('*HANDLER-BINDINGS*');
var l54=internals.intern('SERIOUS-CONDITION','COMMON-LISP');
var l55=internals.make_lisp_string('~A: ~A~%');
var l56=internals.make_lisp_string(': ');
var l57=internals.intern('CLASS-OF','COMMON-LISP');
var l58=internals.intern('CLASS-NAME','COMMON-LISP');
var l59=internals.intern('*TRACE-OUTPUT*','COMMON-LISP');
var l60=internals.intern('FROM','KEYWORD');
l60.value=l60;
var l61=internals.intern('SIGNAL','COMMON-LISP');
var l62=internals.intern('FORMAT-BACKTRACE');
var l63=internals.intern('%%ERROR');
var l64=internals.intern('LIST','COMMON-LISP');
var l65=internals.intern('EVAL-INTERACTIVE-INPUT');
var l66=internals.intern('FRESH-LINE','COMMON-LISP');
var l67=internals.intern('PRIN1','COMMON-LISP');
var l68=internals.intern('SET-FILL-POINTER');
var l69=internals.make_lisp_string('ERROR[!]: ');
var l70=internals.make_lisp_string(': ');
l23.fvalue=(function(){var FUNC=(function JSCL_USER_STARTREPL(){internals.checkArgsAtMost(arguments.length,0);
var v15=this;
return (function(){l24.fvalue();
l22.value=internals.symbolValue(l25)['readline']['createInterface'](internals.symbolValue(l25)['process']['stdin'],internals.symbolValue(l25)['process']['stdout']);
return (function(v17,v18){return (function(v22){v22();
internals.symbolValue(l22)['prompt']();
return internals.symbolValue(l22)['on']('line',(function JSCL_USER_NIL(v58){internals.checkArgs(arguments.length,1);
var v59=this;
l35.fvalue(l34.fvalue(v58),v17);
(function(v60){return l37.fvalue(v60)!==l2.value?internals.symbolValue(l22)['setPrompt'](internals.xstring(v18)):((function(){try{return (function(){try{var v70=[];
return (function(v71){return internals.bindSpecialBindings([l53],[v71],(function(){(function(){var v73=new internals.Cons(l54,(function JSCL_USER_NIL(v74){internals.checkArgs(arguments.length,1);
var v75=this;
l52.fvalue(internals.symbolValue(l39),(function JSCL_USER_NIL(v77,v78,v79){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v78=l46.fvalue(l40,l41.value,l42,l43.value,l55,l45.value,1);
;
case 2:v79=l46.fvalue(l40,l41.value,l42,l43.value,l55,l45.value,5);
;
default:break;
}var v76=l2.value;
var I;
for (I=arguments.length-1;I>=3;I--)v76=new internals.Cons(arguments[I],v76);
var v80=this;
(function(){l49.fvalue(v78,v77);
l48.fvalue(l70,v77);
l49.fvalue(v79,v77);
return l50.fvalue(v77);
})();
return internals.values1(v76);
}),l58.fvalue(l57.fvalue(v74)),v74);
l62.fvalue(internals.symbolValue(l59),l60.value,internals.symbolFunction(l61));
return (function(){throw new internals.BlockNLX(v70,l2.value,null,'BAIL-OUT');
})();
}));
var v82=new internals.Cons(v73,internals.symbolValue(l53));
return l53.value=v82;
})();
return (function(){try{return (function(){return (function(v86,v87){(function(){while (v86!==l2.value){v87=v86.$$jscl_car;
l66.fvalue();
l67.fvalue(v87);
l50.fvalue();
l2.value;
v86=v86.$$jscl_cdr;
}return l2.value;
})();
return l2.value;
})((function(){var FUNC=internals.symbolFunction(l64);
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.mvcall(l65.fvalue,v60);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})(),l2.value);
})();
}catch (v83){return (internals.isNLX(v83)?l38.value:l2.value)!==l2.value?(function(){throw v83;
})():l63.fvalue((function(v84){return (v84===undefined?l38.value:l2.value)!==l2.value?l34.fvalue(v83):l34.fvalue(v84);
})(v83['message']));
}})();
}));
})(internals.symbolValue(l53));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v70) return CF.value;
 else throw CF;
}})();
}catch (v61){return (function(v63){return l52.fvalue(internals.symbolValue(l39),(function JSCL_USER_NIL(v65,v66,v67){internals.checkArgsAtLeast(arguments.length,1);
switch(arguments.length){case 1:v66=l46.fvalue(l40,l41.value,l42,l43.value,l44,l45.value,11);
;
case 2:v67=l46.fvalue(l40,l41.value,l42,l43.value,l44,l45.value,15);
;
default:break;
}var v64=l2.value;
var I;
for (I=arguments.length-1;I>=3;I--)v64=new internals.Cons(arguments[I],v64);
var v68=this;
(function(){l48.fvalue(l69,v65);
l49.fvalue(v66,v65);
l50.fvalue(v65);
l49.fvalue(v67,v65);
return l50.fvalue(v65);
})();
return internals.values1(v64);
}),v63,l34.fvalue(v61['stack']??l51));
})((function(v62){return (v62===undefined?l38.value:l2.value)!==l2.value?l34.fvalue(v61):l34.fvalue(v62);
})(v61['message']));
}})(),(function(){var v89=l36.fvalue(v17);
return (function(){var FUNC=(function JSCL_USER_NIL(v91){switch(arguments.length){case 0:v91=l2.value;
;
default:break;
}var v90=l2.value;
var I;
for (I=arguments.length-1;I>=1;I--)v90=new internals.Cons(arguments[I],v90);
var v92=this;
return internals.mvcall(l68.fvalue,v89,v91);
});
var ARGS=[];
var _R;
_R=internals.withMV((function(){return internals.values1(0);
}));
if (_R.mv!==null) ARGS=ARGS.concat(_R.mv);
 else ARGS.push(_R.result);
return internals.mvcall(FUNC,...ARGS);
})();
})(),v22());
})(l36.fvalue(v17));
return internals.symbolValue(l22)['prompt']();
}));
})((function JSCL_USER_NIL(){internals.checkArgsAtMost(arguments.length,0);
var v19=this;
return (function(){return (function(v21){internals.symbolValue(l22)['setPrompt'](internals.xstring(v21));
return v18=l33.fvalue(l17,l31.fvalue(l29.fvalue(l28.fvalue(v21)),l30.value,'.'),l32);
})(l27.fvalue());
})();
}));
})(l26.fvalue(),l2.value);
})();
});
FUNC.fname=internals.make_lisp_string('START-REPL');
return FUNC;
})();
l23;
var l71=internals.intern('DENO-INIT','JSCL/DENO-REPL');
var l72=internals.intern('*STANDARD-OUTPUT*','COMMON-LISP');
var l73=internals.intern('WRITE-FN','KEYWORD');
l73.value=l73;
var l74=internals.intern('MAKE-STREAM');
var l75=internals.make_lisp_string('CL-USER');
var l76=internals.intern('FIND-PACKAGE','COMMON-LISP');
var l77=internals.intern('SUBSEQ','COMMON-LISP');
var l78=internals.intern('VECTOR-TO-LIST');
var l79=internals.intern('NULL','COMMON-LISP');
var l80=internals.intern('LOAD','COMMON-LISP');
l71.fvalue=(function(){var FUNC=(function JSCL_USER_DENOINIT(){internals.checkArgsAtMost(arguments.length,0);
var v93=this;
return (function(){l72.value=l74.fvalue(l73.value,(function JSCL_USER_NIL(v95){internals.checkArgs(arguments.length,1);
var v96=this;
return internals.symbolValue(l25)['process']['stdout']['write'](internals.xstring(v95));
}));
l39.value=internals.symbolValue(l72);
l59.value=internals.symbolValue(l72);
l19.value=l76.fvalue(l75);
return (function(v97){return l79.fvalue(v97)!==l2.value?internals.mvcall(l23.fvalue):(function(){return (function(v99,v100){(function(){while (v99!==l2.value){v100=v99.$$jscl_car;
l80.fvalue(v100);
l2.value;
v99=v99.$$jscl_cdr;
}return l2.value;
})();
return internals.values1(l2.value);
})(v97,l2.value);
})();
})(l8.fvalue(internals.symbolFunction(l34),l78.fvalue(l77.fvalue(internals.symbolValue(l25)['process']['argv'],2))));
})();
});
FUNC.fname=internals.make_lisp_string('DENO-INIT');
return FUNC;
})();
l71;
l71.fvalue();
})(jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'):
typeof window !== 'undefined'? window.jscl: self.jscl )