if (typeof importScripts !== 'undefined') importScripts('./jscl.js');
(function(jscl){
'use strict';
(function(values, internals){var l1=internals.make_lisp_string('loading deno/repl.lisp!');
console.log(internals.xstring(l1));
var l2=internals.intern('*RL*','JSCL');
l2;
var l3=internals.intern('START-REPL','JSCL');
var l4=internals.intern('WELCOME-MESSAGE','JSCL');
var l5=internals.intern('*ROOT*','JSCL');
var l6=internals.intern('NIL');
var l7=internals.intern('MAKE-STRING-OUTPUT-STREAM');
var l8=internals.intern('*PACKAGE*');
var l9=internals.intern('PACKAGE-NAME-FOR-PROMPT','JSCL');
var l10=internals.intern('FORMAT-ERROR','JSCL');
var l11=internals.intern('COMPLAINT','KEYWORD');
l11.value=l11;
var l12=internals.make_lisp_string('Required argument missing');
var l13=internals.intern('CONTROL-STRING','KEYWORD');
l13.value=l13;
var l14=internals.make_lisp_string('~a> ');
var l15=internals.intern('OFFSET','KEYWORD');
l15.value=l15;
var l16=internals.intern('ERROR');
var l17=internals.intern('PRINC');
var l18=internals.make_lisp_string('> ');
var l19=internals.intern('WRITE-STRING');
var l20=internals.intern('CALL-FORMATTER','JSCL');
var l21=internals.make_lisp_string('> ');
var l22=internals.intern('LENGTH');
var l23=internals.intern('1+');
var l24=internals.intern('INITIAL-ELEMENT','KEYWORD');
l24.value=l24;
var l25=internals.intern('MAKE-STRING');
var l26=internals.make_lisp_string(' ');
var l27=internals.intern('CONCAT','JSCL');
var l28=internals.make_lisp_string('line');
var l29=internals.intern('WRITE-LINE');
var l30=internals.intern('STREAM-DATA','JSCL');
var l31=internals.intern('%SEXPR-INCOMPLETE','JSCL');
var l32=internals.intern('*ERROR-OUTPUT*');
var l33=internals.make_lisp_string('ERROR[!]: ~a~%~A~%');
var l34=internals.make_lisp_string('ERROR[!]: ');
var l35=internals.intern('TERPRI');
var l36=internals.intern('*HANDLER-BINDINGS*','JSCL');
var l37=internals.intern('SERIOUS-CONDITION');
var l38=internals.make_lisp_string('~A: ~A~%');
var l39=internals.make_lisp_string(': ');
var l40=internals.intern('CLASS-OF');
var l41=internals.intern('CLASS-NAME');
var l42=internals.intern('*TRACE-OUTPUT*');
var l43=internals.intern('FROM','KEYWORD');
l43.value=l43;
var l44=internals.intern('SIGNAL');
var l45=internals.intern('FORMAT-BACKTRACE','JSCL');
var l46=internals.intern('T');
var l47=internals.intern('%%ERROR','JSCL');
var l48=internals.intern('LIST');
var l49=internals.intern('EVAL-INTERACTIVE-INPUT','JSCL');
var l50=internals.intern('FRESH-LINE');
var l51=internals.intern('PRIN1');
var l52=internals.intern('SET-FILL-POINTER','JSCL');
var l53=internals.make_lisp_string('ERROR[!]: ');
var l54=internals.make_lisp_string(': ');
l3.fvalue=(function(){var FUNC=(function JSCL_USER_STARTREPL(values){internals.checkArgsAtMost(arguments.length-1,0);
var v1=this;
return (function(){l4.fvalue(internals.pv);
l2.value=internals.js_to_lisp(internals.symbolValue(l5)['readline']['createInterface'](internals.lisp_to_js(internals.js_to_lisp((function(){var TMP=internals.symbolValue(l5)['process'];
if (TMP===undefined) return l6.value;
TMP=TMP['stdin'];
return TMP===undefined?l6.value:TMP;
})())),internals.lisp_to_js(internals.js_to_lisp((function(){var TMP=internals.symbolValue(l5)['process'];
if (TMP===undefined) return l6.value;
TMP=TMP['stdout'];
return TMP===undefined?l6.value:TMP;
})()))));
return (function(v3,v4){return (function(v18){v18(internals.pv);
internals.js_to_lisp(internals.symbolValue(l2)['prompt']());
return internals.js_to_lisp(internals.symbolValue(l2)['on'](internals.lisp_to_js(l28),internals.lisp_to_js((function JSCL_USER_NIL(values,v54){internals.checkArgs(arguments.length-1,1);
var v55=this;
l29.fvalue(internals.pv,v54,v3);
(function(v56){return l31.fvalue(internals.pv,v56)!==l6.value?internals.js_to_lisp(internals.symbolValue(l2)['setPrompt'](internals.lisp_to_js(v4))):((function(){try{return (function(){try{var v66=[];
return (function(v67){return internals.bindSpecialBindings([l36],[v67],(function(){(function(){var v69=new internals.Cons(l37,(function JSCL_USER_NIL(values,v70){internals.checkArgs(arguments.length-1,1);
var v71=this;
l20.fvalue(internals.pv,internals.symbolValue(l32),(function JSCL_USER_NIL(values,v73,v74,v75){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v74=l16.fvalue(internals.pv,l10,l11.value,l12,l13.value,l38,l15.value,1);
;
case 2:v75=l16.fvalue(internals.pv,l10,l11.value,l12,l13.value,l38,l15.value,5);
;
default:break;
}var v72=l6.value;
var I;
for (I=arguments.length-1-1;I>=3;I--)v72=new internals.Cons(arguments[I+1],v72);
var v76=this;
(function(){l17.fvalue(internals.pv,v74,v73);
l19.fvalue(internals.pv,l54,v73);
l17.fvalue(internals.pv,v75,v73);
return l35.fvalue(internals.pv,v73);
})();
return v72;
}),l41.fvalue(internals.pv,l40.fvalue(internals.pv,v70)),v70);
l45.fvalue(internals.pv,internals.symbolValue(l42),l43.value,internals.symbolFunction(l44));
return (function(){throw new internals.BlockNLX(v66,l6.value,'BAIL-OUT');
})();
}));
var v78=new internals.Cons(v69,internals.symbolValue(l36));
return l36.value=v78;
})();
return (function(){try{return (function(){return (function(v82,v83){(function(){while (v82!==l6.value){v83=v82.$$jscl_car;
l50.fvalue(internals.pv);
l51.fvalue(internals.pv,v83);
l35.fvalue(internals.pv);
l6.value;
v82=v82.$$jscl_cdr;
}return l6.value;
})();
return l6.value;
})((function(){var FUNC=internals.symbolFunction(l48);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l49.fvalue(values,v56);
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})(),l6.value);
})();
}catch (v79){v79=internals.js_to_lisp(v79);
return (internals.isNLX(v79)?l46.value:l6.value)!==l6.value?(function(){throw v79;
})():l47.fvalue(internals.pv,(function(v80){return v80!==l6.value?v80:v79;
})(internals.js_to_lisp((function(){var TMP=v79['message'];
return TMP===undefined?l6.value:TMP;
})())));
}})();
}));
})(internals.symbolValue(l36));
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v66) return CF.values;
 else throw CF;
}})();
}catch (v57){v57=internals.js_to_lisp(v57);
return (function(v59){return l20.fvalue(internals.pv,internals.symbolValue(l32),(function JSCL_USER_NIL(values,v61,v62,v63){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v62=l16.fvalue(internals.pv,l10,l11.value,l12,l13.value,l33,l15.value,11);
;
case 2:v63=l16.fvalue(internals.pv,l10,l11.value,l12,l13.value,l33,l15.value,15);
;
default:break;
}var v60=l6.value;
var I;
for (I=arguments.length-1-1;I>=3;I--)v60=new internals.Cons(arguments[I+1],v60);
var v64=this;
(function(){l19.fvalue(internals.pv,l53,v61);
l17.fvalue(internals.pv,v62,v61);
l35.fvalue(internals.pv,v61);
l17.fvalue(internals.pv,v63,v61);
return l35.fvalue(internals.pv,v61);
})();
return v60;
}),v59,internals.js_to_lisp((function(){var TMP=v57['stack'];
return TMP===undefined?l6.value:TMP;
})()));
})((function(v58){return v58!==l6.value?v58:v57;
})(internals.js_to_lisp((function(){var TMP=v57['message'];
return TMP===undefined?l6.value:TMP;
})())));
}})(),(function(){var v85=l30.fvalue(internals.pv,v3);
return (function(){var FUNC=(function JSCL_USER_NIL(values,v87){switch(arguments.length-1){case 0:v87=l6.value;
;
default:break;
}var v86=l6.value;
var I;
for (I=arguments.length-1-1;I>=1;I--)v86=new internals.Cons(arguments[I+1],v86);
var v88=this;
return l52.fvalue(values,v85,v87);
});
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=0;
if (typeof VS==='object'&&VS&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
})(),v18(internals.pv));
})(l30.fvalue(internals.pv,v3));
return internals.js_to_lisp(internals.symbolValue(l2)['prompt']());
}))));
})((function JSCL_USER_NIL(values){internals.checkArgsAtMost(arguments.length-1,0);
var v5=this;
return (function(){return (function(v7){internals.js_to_lisp(internals.symbolValue(l2)['setPrompt'](internals.lisp_to_js(l20.fvalue(internals.pv,l6.value,(function JSCL_USER_NIL(values,v14,v15){internals.checkArgsAtLeast(arguments.length-1,1);
switch(arguments.length-1){case 1:v15=l16.fvalue(internals.pv,l10,l11.value,l12,l13.value,l14,l15.value,1);
;
default:break;
}var v13=l6.value;
var I;
for (I=arguments.length-1-1;I>=2;I--)v13=new internals.Cons(arguments[I+1],v13);
var v16=this;
(function(){l17.fvalue(internals.pv,v15,v14);
return l19.fvalue(internals.pv,l21,v14);
})();
return v13;
}),v7))));
return v4=l27.fvalue(internals.pv,l25.fvalue(internals.pv,l23.fvalue(internals.pv,l22.fvalue(internals.pv,v7)),l24.value,'.'),l26);
})(l9.fvalue(internals.pv,internals.symbolValue(l8)));
})();
}));
})(l7.fvalue(internals.pv),l6.value);
})();
});
FUNC.fname='START-REPL';
return FUNC;
})();
l3;
var l55=internals.intern('DENO-INIT','JSCL');
var l56=internals.intern('*STANDARD-OUTPUT*');
var l57=internals.intern('WRITE-FN','KEYWORD');
l57.value=l57;
var l58=internals.intern('MAKE-STREAM','JSCL');
var l59=internals.intern('JS-TO-LISP','JSCL');
var l60=internals.intern('SUBSEQ');
var l61=internals.intern('VECTOR-TO-LIST','JSCL');
var l62=internals.intern('MAPCAR');
var l63=internals.intern('NULL');
var l64=internals.intern('LOAD');
l55.fvalue=(function(){var FUNC=(function JSCL_USER_DENOINIT(values){internals.checkArgsAtMost(arguments.length-1,0);
var v89=this;
return (function(){l56.value=l58.fvalue(internals.pv,l57.value,(function JSCL_USER_NIL(values,v91){internals.checkArgs(arguments.length-1,1);
var v92=this;
return internals.js_to_lisp(internals.symbolValue(l5)['process']['stdout']['write'](internals.lisp_to_js(v91)));
}));
l32.value=internals.symbolValue(l56);
l42.value=internals.symbolValue(l56);
return (function(v93){return l63.fvalue(internals.pv,v93)!==l6.value?l3.fvalue(values):(function(){return (function(v95,v96){(function(){while (v95!==l6.value){v96=v95.$$jscl_car;
l64.fvalue(internals.pv,v96);
l6.value;
v95=v95.$$jscl_cdr;
}return l6.value;
})();
return l6.value;
})(v93,l6.value);
})();
})(l62.fvalue(internals.pv,internals.symbolFunction(l59),l61.fvalue(internals.pv,l60.fvalue(internals.pv,internals.js_to_lisp((function(){var TMP=internals.symbolValue(l5)['process'];
if (TMP===undefined) return l6.value;
TMP=TMP['argv'];
return TMP===undefined?l6.value:TMP;
})()),2))));
})();
});
FUNC.fname='DENO-INIT';
return FUNC;
})();
l55;
l55.fvalue(internals.pv);
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'):
typeof window !== 'undefined'? window.jscl: self.jscl )