(function(jscl){
'use strict';
(function(values, internals){
var l1=internals.make_lisp_string('loading repl-web/repl.lisp!');
console.log(internals.xstring(l1));
var l2=internals.intern('%WRITE-STRING');
var l3=internals.intern('T','COMMON-LISP');
var l4=internals.intern('*ROOT*');
var l5=internals.make_lisp_string('jqconsole');
var l6=internals.intern('NIL','COMMON-LISP');
var l7=internals.make_lisp_string('jqconsole-output');
var l8=internals.make_lisp_string('');
var l9=internals.make_lisp_string('jqconsole');
var l10=internals.make_lisp_string('Write');
var l11=internals.make_lisp_string('console');
var l12=internals.make_lisp_string('log');
l2.fvalue=(function(){var FUNC=(function(values,v1,v2){internals.checkArgsAtLeast(arguments.length-1,1);
internals.checkArgsAtMost(arguments.length-1,2);
switch(arguments.length-1){case 1:v2=l3.value;
;
default:break;
}return (function(){return internals.js_to_lisp((function(){var TMP=internals.symbolValue(l4)[internals.xstring(l5)];
return TMP===undefined?l6.value:TMP;
})())!==l6.value?internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l9)][internals.xstring(l10)](internals.lisp_to_js(v1),internals.lisp_to_js(l7),internals.lisp_to_js(l8),internals.lisp_to_js(v2))):internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l11)][internals.xstring(l12)](internals.lisp_to_js(v1)));
})();
});
FUNC.fname='%WRITE-STRING';
return FUNC;
})();
l2;
var l13=internals.intern('LOAD-HISTORY');
var l14=internals.make_lisp_string('jqhist');
var l15=internals.make_lisp_string('localStorage');
var l16=internals.make_lisp_string('getItem');
var l17=internals.make_lisp_string('JSON');
var l18=internals.make_lisp_string('parse');
var l19=internals.make_lisp_string('jqconsole');
var l20=internals.make_lisp_string('SetHistory');
l13.fvalue=(function(){var FUNC=(function(values){internals.checkArgsAtMost(arguments.length-1,0);
return (function(){return (function(v5){return (v5===null?l3.value:l6.value)!==l6.value?l6.value:internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l19)][internals.xstring(l20)](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l17)][internals.xstring(l18)](internals.lisp_to_js(v5))))));
})(internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l15)][internals.xstring(l16)](internals.lisp_to_js(l14))));
})();
});
FUNC.fname='LOAD-HISTORY';
return FUNC;
})();
l13;
var l21=internals.intern('SAVE-HISTORY');
var l22=internals.make_lisp_string('jqhist');
var l23=internals.make_lisp_string('jqconsole');
var l24=internals.make_lisp_string('GetHistory');
var l25=internals.make_lisp_string('JSON');
var l26=internals.make_lisp_string('stringify');
var l27=internals.make_lisp_string('localStorage');
var l28=internals.make_lisp_string('setItem');
l21.fvalue=(function(){var FUNC=(function(values){internals.checkArgsAtMost(arguments.length-1,0);
return (function(){return internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l27)][internals.xstring(l28)](internals.lisp_to_js(l22),internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l25)][internals.xstring(l26)](internals.lisp_to_js(internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l23)][internals.xstring(l24)]())))))));
})();
});
FUNC.fname='SAVE-HISTORY';
return FUNC;
})();
l21;
var l29=internals.intern('INDENT-LEVEL');
var l30=internals.intern('LENGTH','COMMON-LISP');
var l31=internals.intern('CHAR','COMMON-LISP');
var l32=internals.intern('EQL','COMMON-LISP');
var l33=internals.intern('ZEROP','COMMON-LISP');
l29.fvalue=(function(){var FUNC=(function(values,v7){internals.checkArgs(arguments.length-1,1);
return (function(){return (function(v9,v10,v11,v12){(function(){return (function(){while ((function(){var x1=v9;
if (typeof x1!='number') throw 'Not a number!';
var x2=v11;
if (typeof x2!='number') throw 'Not a number!';
return x1<x2?l3.value:l6.value;
})()!==l6.value){if (v10!==l6.value) (function(v14){return l32.fvalue(internals.pv,v14,'\\')!==l6.value?(l6.value,(function(){var v15=1;
var v16=(function(){var x1=v9;
if (typeof x1!='number') throw 'Not a number!';
var x2=v15;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v9=v16;
})()):l32.fvalue(internals.pv,v14,'"')!==l6.value?(l6.value,(v10=l6.value),(function(){var v17=1;
var v18=(function(){var x1=v12;
if (typeof x1!='number') throw 'Not a number!';
var x2=v17;
if (typeof x2!='number') throw 'Not a number!';
return x1-x2;
})();
return v12=v18;
})()):l6.value;
})(l31.fvalue(internals.pv,v7,v9));
 else (function(v19){return l32.fvalue(internals.pv,v19,'(')!==l6.value?(l6.value,(function(){var v20=1;
var v21=(function(){var x1=v12;
if (typeof x1!='number') throw 'Not a number!';
var x2=v20;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v12=v21;
})()):l32.fvalue(internals.pv,v19,')')!==l6.value?(l6.value,(function(){var v22=1;
var v23=(function(){var x1=v12;
if (typeof x1!='number') throw 'Not a number!';
var x2=v22;
if (typeof x2!='number') throw 'Not a number!';
return x1-x2;
})();
return v12=v23;
})()):l32.fvalue(internals.pv,v19,'"')!==l6.value?(l6.value,(function(){var v24=1;
var v25=(function(){var x1=v12;
if (typeof x1!='number') throw 'Not a number!';
var x2=v24;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v12=v25;
})(),v10=l3.value):l6.value;
})(l31.fvalue(internals.pv,v7,v9));
(function(){var v26=1;
var v27=(function(){var x1=v9;
if (typeof x1!='number') throw 'Not a number!';
var x2=v26;
if (typeof x2!='number') throw 'Not a number!';
return x1+x2;
})();
return v9=v27;
})();
}return l6.value;
})();
})();
return l33.fvalue(internals.pv,v12)!==l6.value?l6.value:0;
})(0,l6.value,l30.fvalue(internals.pv,v7),0);
})();
});
FUNC.fname='INDENT-LEVEL';
return FUNC;
})();
l29;
var l34=internals.intern('TOPLEVEL');
var l35=internals.make_lisp_string('(');
var l36=internals.make_lisp_string(')');
var l37=internals.make_lisp_string('parents');
var l38=internals.make_lisp_string('jqconsole');
var l39=internals.make_lisp_string('RegisterMatching');
var l40=internals.make_lisp_string('~a> ');
var l41=internals.intern('*PACKAGE*','COMMON-LISP');
var l42=internals.intern('PACKAGE-NAME','COMMON-LISP');
var l43=internals.intern('FORMAT','COMMON-LISP');
var l44=internals.make_lisp_string('jqconsole-prompt');
var l45=internals.make_lisp_string('jqconsole');
var l46=internals.make_lisp_string('Write');
var l47=internals.make_lisp_string('console');
var l48=internals.make_lisp_string('log');
var l49=internals.make_lisp_string('message');
var l50=internals.make_lisp_string('ERROR[!]: ~a~%');
var l51=internals.make_lisp_string('jqconsole-error');
var l52=internals.make_lisp_string('jqconsole');
var l53=internals.make_lisp_string('Write');
var l54=internals.intern('*HANDLER-BINDINGS*');
var l55=internals.intern('ERROR','COMMON-LISP');
var l56=internals.make_lisp_string('message');
var l57=internals.intern('%ERROR');
var l58=internals.intern('READ-FROM-STRING','COMMON-LISP');
var l59=internals.intern('LIST','COMMON-LISP');
var l60=internals.intern('EVAL-INTERACTIVE');
var l61=internals.make_lisp_string('~S~%');
var l62=internals.make_lisp_string('jqconsole-return');
var l63=internals.make_lisp_string('jqconsole');
var l64=internals.make_lisp_string('Write');
var l65=internals.make_lisp_string('ERROR: ');
var l66=internals.make_lisp_string('jqconsole-error');
var l67=internals.make_lisp_string('jqconsole');
var l68=internals.make_lisp_string('Write');
var l69=internals.intern('!CONDITION-ARGS');
var l70=internals.make_lisp_string('jqconsole-error');
var l71=internals.make_lisp_string('jqconsole');
var l72=internals.make_lisp_string('Write');
var l73=internals.intern('STRING','COMMON-LISP');
var l74=internals.make_lisp_string('jqconsole-error');
var l75=internals.make_lisp_string('jqconsole');
var l76=internals.make_lisp_string('Write');
var l77=internals.make_lisp_string('jqconsole');
var l78=internals.make_lisp_string('Prompt');
l34.fvalue=(function(){var FUNC=(function(values){internals.checkArgsAtMost(arguments.length-1,0);
return (function(){internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l38)][internals.xstring(l39)](internals.lisp_to_js(l35),internals.lisp_to_js(l36),internals.lisp_to_js(l37)));
(function(v29){return internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l45)][internals.xstring(l46)](internals.lisp_to_js(v29),internals.lisp_to_js(l44)));
})(l43.fvalue(internals.pv,l6.value,l40,l42.fvalue(internals.pv,internals.symbolValue(l41))));
return (function(v51){return internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l77)][internals.xstring(l78)](internals.lisp_to_js(l3.value),internals.lisp_to_js(v51),internals.lisp_to_js(internals.symbolFunction(l29))));
})((function(values,v30){internals.checkArgs(arguments.length-1,1);
return (function(){(function(){try{return (function(){try{var v35=[];
return (function(v36){return (function(){var v37=1;
var v38=[];
TBLOOP:while (true){try{switch(v37){case 1:(function(v39){return internals.bindSpecialBindings([l54],[v39],(function(){(function(){var v40=new internals.Cons(l55,(function(values,v41){internals.checkArgs(arguments.length-1,1);
v36=v41;
return (function(){throw new internals.TagNLX(v38,2);
})();
}));
var v42=new internals.Cons(v40,internals.symbolValue(l54));
return l54.value=v42;
})();
return (function(){try{return (function(){throw new internals.BlockNLX(v35,(function(){var v45=l58.fvalue(internals.pv,v30);
var v46=(function(){var FUNC=internals.symbolFunction(l59);
var ARGS=[internals.pv];
return (function(){var values=internals.mv;
var VS;
VS=l60.fvalue(values,v45);
if (typeof VS==='object'&&'multiple-value' in VS) ARGS=ARGS.concat(VS);
 else ARGS.push(VS);
return FUNC.apply(null,ARGS);
})();
})();
return (function(){return (function(v48,v49){(function(){while (v48!==l6.value){v49=internals.car(v48);
internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l63)][internals.xstring(l64)](internals.lisp_to_js(l43.fvalue(internals.pv,l6.value,l61,v49)),internals.lisp_to_js(l62)));
l6.value;
v48=internals.cdr(v48);
}return l6.value;
})();
return l6.value;
})(v46,l6.value);
})();
})(),'G283');
})();
}catch (v43){v43=internals.js_to_lisp(v43);
return (internals.isNLX(v43)?l3.value:l6.value)!==l6.value?(function(){throw v43;
})():l57.fvalue(internals.pv,(function(v44){return v44!==l6.value?v44:v43;
})(internals.js_to_lisp((function(){var TMP=v43[internals.xstring(l56)];
return TMP===undefined?l6.value:TMP;
})())));
}})();
}));
})(internals.symbolValue(l54));
case 2:(function(){throw new internals.BlockNLX(v35,(function(v50){internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l67)][internals.xstring(l68)](internals.lisp_to_js(l65),internals.lisp_to_js(l66)));
internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l71)][internals.xstring(l72)](internals.lisp_to_js((function(){var F=internals.symbolFunction(l43);
var ARGS=[internals.pv,l6.value];
var TAIL=l69.fvalue(internals.pv,v50);
while (TAIL!=l6.value){ARGS.push(TAIL.car);
TAIL=TAIL.cdr;
}return (typeof F==='function'?F:F.fvalue).apply(this,ARGS);
})()),internals.lisp_to_js(l70)));
return internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l75)][internals.xstring(l76)](internals.lisp_to_js(l73.fvalue(internals.pv,'\n')),internals.lisp_to_js(l74)));
})(v36),'G283');
})();
default:break TBLOOP;
}}catch (JUMP){if (JUMP instanceof internals.TagNLX&&JUMP.id==v38) v37=JUMP.label;
 else throw JUMP;
}}return l6.value;
})();
})(l6.value);
}catch (CF){if (CF instanceof internals.BlockNLX&&CF.id==v35) return CF.values;
 else throw CF;
}})();
}catch (v32){v32=internals.js_to_lisp(v32);
internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l47)][internals.xstring(l48)](internals.lisp_to_js(v32)));
return (function(v34){return internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l52)][internals.xstring(l53)](internals.lisp_to_js(l43.fvalue(internals.pv,l6.value,l50,v34)),internals.lisp_to_js(l51)));
})((function(v33){return v33!==l6.value?v33:v32;
})(internals.js_to_lisp((function(){var TMP=v32[internals.xstring(l49)];
return TMP===undefined?l6.value:TMP;
})())));
}})();
l21.fvalue(internals.pv);
return l34.fvalue(values);
})();
}));
})();
});
FUNC.fname='TOPLEVEL';
return FUNC;
})();
l34;
var l79=internals.intern('WEB-INIT');
var l80=internals.intern('*STANDARD-OUTPUT*','COMMON-LISP');
var l81=internals.intern('STREAM','COMMON-LISP');
var l82=internals.intern('VECTOR','COMMON-LISP');
var l83=internals.intern('WELCOME-MESSAGE');
var l84=internals.make_lisp_string('load');
var l85=internals.make_lisp_string('window');
var l86=internals.make_lisp_string('addEventListener');
l79.fvalue=(function(){var FUNC=(function(values){internals.checkArgsAtMost(arguments.length-1,0);
return (function(){l13.fvalue(internals.pv);
l80.value=l82.fvalue(internals.pv,l81,(function(values,v53){internals.checkArgs(arguments.length-1,1);
return l2.fvalue(values,l73.fvalue(internals.pv,v53));
}),(function(values,v54){internals.checkArgs(arguments.length-1,1);
return l2.fvalue(values,v54);
}));
l83.fvalue(internals.pv);
return internals.js_to_lisp(internals.symbolValue(l4)[internals.xstring(l85)][internals.xstring(l86)](internals.lisp_to_js(l84),internals.lisp_to_js((function(values){var v56=l6.value;
var I;
for (I=arguments.length-1-1;I>=0;I--)v56=new internals.Cons(arguments[I+1],v56);
return l34.fvalue(values);
}))));
})();
});
FUNC.fname='WEB-INIT';
return FUNC;
})();
l79;
l79.fvalue(internals.pv);
})(jscl.internals.pv, jscl.internals);
})( typeof require !== 'undefined'? require('./jscl'): window.jscl )
